"""All models. Import this module to populate Base.metadata."""

from __future__ import annotations

from cafeops.db.base import Base
from cafeops.db.models.agent_proposal import AgentProposal
from cafeops.db.models.auth import AuthAudit, AuthCredential, AuthSession
from cafeops.db.models.batch import Season, StockBatch
from cafeops.db.models.channel import (
    AgentActionLog,
    ChannelItemMetric,
    ChannelMetric,
    TescoRouting,
)
from cafeops.db.models.composition import (
    DrinkTemplate,
    LegacyStagedRecipe,
    Modifier,
    ModifierVersion,
    RecipeChange,
    SizeProfile,
    TemplateComponent,
    VariantAxis,
    VariantOption,
)
from cafeops.db.models.enums import (
    AgentToolOutcome,
    AuthEvent,
    ChannelSourceKind,
    ChecklistStatus,
    ComponentRole,
    DirectorEntryType,
    ExpenseGroup,
    ExpenseKind,
    ExpenseMethod,
    ExpirySource,
    FinanceSource,
    MenuKind,
    MenuPriceSource,
    ModifierAction,
    MovementType,
    OrderChannel,
    PaymentBasis,
    POStatus,
    PriceSource,
    ProposalConfidence,
    ProposalKind,
    ProposalStatus,
    SaleChannel,
    SalesChannelName,
    SizeCode,
    Storage,
    SyncSource,
    SyncStatus,
    SyncTrigger,
    Tier,
    Unit,
    WriteOffReason,
)
from cafeops.db.models.finance import (
    CardPayout,
    CashCount,
    ChannelStatement,
    DirectorEntry,
    Expense,
    ExpenseCategory,
    FinanceSetting,
    TradingDay,
)
from cafeops.db.models.ingredient import Ingredient, IngredientPrice, IngredientTierChange
from cafeops.db.models.loyalty import (
    CampaignSegment,
    LoyaltyAudit,
    LoyaltyCampaign,
    LoyaltyCampaignDelivery,
    LoyaltyCard,
    LoyaltyMember,
    LoyaltyOtp,
    LoyaltyPosAward,
    LoyaltyPosReceipt,
    LoyaltyProgram,
    LoyaltyReward,
    LoyaltyRewardOption,
    LoyaltyStampEvent,
    OtpChannel,
    PosAwardStatus,
    ProgramKind,
    RewardKind,
    StampReason,
    WalletPushOutbox,
)
from cafeops.db.models.media import MediaAsset
from cafeops.db.models.menu import (
    ManualRecipeLine,
    MenuCategory,
    MenuItem,
    MenuItemCost,
    MenuItemPrice,
    MenuItemReference,
)
from cafeops.db.models.par import ParLevel
from cafeops.db.models.payment import PaymentDay
from cafeops.db.models.purchase_order import ChecklistResponse, POLine, PurchaseOrder
from cafeops.db.models.sale import Sale
from cafeops.db.models.staff import StaffDevice, StaffRole, StaffSession, StaffUser
from cafeops.db.models.stock import DriftObservation, StockCount, StockMovement
from cafeops.db.models.supplier import Supplier, SupplierProduct
from cafeops.db.models.sync_run import SyncRun

__all__ = [
    "AgentActionLog",
    "AgentProposal",
    "AgentToolOutcome",
    "AuthAudit",
    "AuthCredential",
    "AuthEvent",
    "AuthSession",
    "Base",
    "CampaignSegment",
    "CardPayout",
    "CashCount",
    "ChannelItemMetric",
    "ChannelMetric",
    "ChannelSourceKind",
    "ChannelStatement",
    "ChecklistResponse",
    "ChecklistStatus",
    "ComponentRole",
    "DirectorEntry",
    "DirectorEntryType",
    "DriftObservation",
    "DrinkTemplate",
    "Expense",
    "ExpenseCategory",
    "ExpenseGroup",
    "ExpenseKind",
    "ExpenseMethod",
    "ExpirySource",
    "FinanceSetting",
    "FinanceSource",
    "Ingredient",
    "IngredientPrice",
    "IngredientTierChange",
    "LegacyStagedRecipe",
    "LoyaltyAudit",
    "LoyaltyCampaign",
    "LoyaltyCampaignDelivery",
    "LoyaltyCard",
    "LoyaltyMember",
    "LoyaltyOtp",
    "LoyaltyPosAward",
    "LoyaltyPosReceipt",
    "LoyaltyProgram",
    "LoyaltyReward",
    "LoyaltyRewardOption",
    "LoyaltyStampEvent",
    "ManualRecipeLine",
    "MediaAsset",
    "MenuCategory",
    "MenuItem",
    "MenuItemCost",
    "MenuItemPrice",
    "MenuItemReference",
    "MenuKind",
    "MenuPriceSource",
    "Modifier",
    "ModifierAction",
    "ModifierVersion",
    "MovementType",
    "OrderChannel",
    "OtpChannel",
    "POLine",
    "POStatus",
    "ParLevel",
    "PaymentBasis",
    "PaymentDay",
    "PosAwardStatus",
    "PriceSource",
    "ProgramKind",
    "ProposalConfidence",
    "ProposalKind",
    "ProposalStatus",
    "PurchaseOrder",
    "RecipeChange",
    "RewardKind",
    "Sale",
    "SaleChannel",
    "SalesChannelName",
    "Season",
    "SizeCode",
    "SizeProfile",
    "StaffDevice",
    "StaffRole",
    "StaffSession",
    "StaffUser",
    "StampReason",
    "StockBatch",
    "StockCount",
    "StockMovement",
    "Storage",
    "Supplier",
    "SupplierProduct",
    "SyncRun",
    "SyncSource",
    "SyncStatus",
    "SyncTrigger",
    "TemplateComponent",
    "TescoRouting",
    "Tier",
    "TradingDay",
    "Unit",
    "VariantAxis",
    "VariantOption",
    "WalletPushOutbox",
    "WriteOffReason",
]

# Wallet tables (loyalty Agent B), appended so parallel edits above do not collide.
from cafeops.db.models.wallet import WalletAppleRegistration, WalletGoogleObject

__all__ += ["WalletAppleRegistration", "WalletGoogleObject"]
