"""po_line: structured cap kind and per-line low confidence

Revision ID: 2910136e57f5
Revises: 2f2a3f1b75cb
Create Date: 2026-09-23 18:10:48.705023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cafeops.db.types  # custom column types (Qty, UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = '2910136e57f5'
down_revision: Union[str, Sequence[str], None] = '2f2a3f1b75cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cap_kind', sa.Enum('SHELF_LIFE', 'SEASON_END', 'OUT_OF_SEASON', 'TOP_UP_MINIMUM', 'TOP_UP_FREE_DELIVERY', 'OTHER', name='capkind', native_enum=False), nullable=True))
        batch_op.add_column(sa.Column('low_confidence', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('low_confidence_kind', sa.Enum('THIN_HISTORY', 'NO_HISTORY', 'NO_PRIOR_SEASON', 'UNTRUSTWORTHY_STOCK', 'OTHER', name='lowconfidencekind', native_enum=False), nullable=True))
        batch_op.add_column(sa.Column('confidence_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po_line', schema=None) as batch_op:
        batch_op.drop_column('confidence_reason')
        batch_op.drop_column('low_confidence_kind')
        batch_op.drop_column('low_confidence')
        batch_op.drop_column('cap_kind')

    # ### end Alembic commands ###
