"""prep time estimate flags

Adds a three-state estimate flag beside every prep time (spec 4.2, 5.6).

`drink_template.prep_seconds_by_size` and `menu_item.prep_seconds` already existed
and carried a number with no provenance. Every prep time in this system today is a
plausible guess, and a margin-per-minute ranking built on guesses must say so on the
screen that shows it -- the same treatment prices (`ingredient_price.source`) and
shelf lives (`ingredient.shelf_life_source`) already get, for the reason invariant 8
exists.

NULL means nothing is recorded, True means estimated, False means somebody timed it.
Nullable, so no DDL default is needed and no existing row is given a provenance it
does not have.

`menu_item_cost` gets the flag too, cached alongside `prep_seconds` rather than
joined back to the template, for the same reason `cost_source` is cached there: an
aggregate that needs a second query to tell estimates from measurements will not
make one.

Revision ID: 2f2a3f1b75cb
Revises: a73b90bd6cb4
Create Date: 2026-09-19 15:39:40.539269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cafeops.db.types  # custom column types (Qty, UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = "2f2a3f1b75cb"
down_revision: Union[str, Sequence[str], None] = "a73b90bd6cb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drink_template", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prep_seconds_is_estimate", sa.Boolean(), nullable=True))

    with op.batch_alter_table("menu_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prep_seconds_is_estimate", sa.Boolean(), nullable=True))

    with op.batch_alter_table("menu_item_cost", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prep_seconds_is_estimate", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("menu_item_cost", schema=None) as batch_op:
        batch_op.drop_column("prep_seconds_is_estimate")

    with op.batch_alter_table("menu_item", schema=None) as batch_op:
        batch_op.drop_column("prep_seconds_is_estimate")

    with op.batch_alter_table("drink_template", schema=None) as batch_op:
        batch_op.drop_column("prep_seconds_is_estimate")

    # ### end Alembic commands ###
