"""back-office redesign data foundation

Every table and column the four redesign specs (docs/design/specs/finance.md,
stock-orders-suppliers.md, recipes-menu-ingredients.md, shell-agents.md) propose,
reconciled with DECISIONS.md. The field-by-field reference is
docs/design/specs/DATA-MODEL.md.

New tables (19): finance -- trading_day, expense_category, expense, cash_count,
card_payout, finance_setting, channel_statement, director_entry; auth -- auth_credential,
auth_session, auth_audit; sync_run; agent_proposal; media_asset; menu_item_price,
menu_category, modifier_version, recipe_change; ingredient_tier_change.

New columns on existing tables, plus CHECKs autogenerate cannot see (Alembic does not
compare CHECK constraints): stock_movement (reason/type pairing, signed write-offs,
OTHER needs a note), purchase_order (CANCELLED needs a human), supplier /
supplier_product (archive signed), ingredient (retire signed).

Enum widening: payment_day.method (+CASH_OFF_TILL), payment_day.source and
channel_metric/channel_item_metric.source (+LEGACY_WORKBOOK). Enums are VARCHAR with no
CHECK here (`native_enum=False`, SQLAlchemy 2.0 creates no constraint), so only the
declared length changes.

Data, reference only -- no transactional data:
- the 13 expense categories ("Square fees" renamed "Card fees", DECISIONS.md 4) and the
  single finance_setting row;
- menu_item_price: one open BACKFILL row per menu item, carrying its current price;
- modifier_version: one open version per modifier, copying its current behaviour;
- stock_batch.expiry_source = ASSUMED where the note carries the EXPIRY ASSUMED stamp;
- purchase_order rows already CANCELLED (none expected) get cancelled_by
  "(not recorded)" so the new CHECK can be added.
The backfilled effective_from is the earliest sale, or now if there are none: prices
before tracking began are unknown, and no sale predates that instant.

Downgrade refuses while any row uses a value the old schema cannot represent.

Revision ID: 62aa94a23687
Revises: dff1f404b11c
Create Date: 2026-09-26 10:10:09.299954

"""
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cafeops.db.types  # custom column types (Qty, UTCDateTime)


#: Seeded verbatim from the workbook's validation list (Expenses!L5:L17), em dash kept,
#: except "Square fees" -> "Card fees" (DECISIONS.md 4; the POS is Lightspeed now).
EXPENSE_CATEGORIES: list[tuple[str, str]] = [
    ('Stock \u2014 coffee', 'COGS'),
    ('Stock \u2014 dairy', 'COGS'),
    ('Stock \u2014 syrups', 'COGS'),
    ('Stock \u2014 cakes', 'COGS'),
    ('Stock \u2014 food', 'COGS'),
    ('Stock \u2014 packaging', 'COGS'),
    ('Stock \u2014 other', 'COGS'),
    ('Rent', 'OPEX'),
    ('Utilities', 'OPEX'),
    ('Wages', 'OPEX'),
    ('Marketing', 'OPEX'),
    ('Card fees', 'OPEX'),
    ('Other', 'OPEX'),
]

# revision identifiers, used by Alembic.
revision: str = '62aa94a23687'
down_revision: Union[str, Sequence[str], None] = 'dff1f404b11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('algo', sa.String(length=20), nullable=False),
    sa.Column('set_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('set_via', sa.String(length=20), nullable=False),
    sa.Column('set_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint("algo = 'scrypt'", name=op.f('ck_auth_credential_algo_scrypt')),
    sa.CheckConstraint('id = 1', name=op.f('ck_auth_credential_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_credential'))
    )
    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.CheckConstraint('(revoked_at IS NULL) = (revoked_reason IS NULL)', name=op.f('ck_auth_session_revoked_has_reason')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_session_token_hash'))
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index('ix_auth_session_active', ['revoked_at', 'expires_at'], unique=False)

    op.create_table('card_payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sold_on', sa.Date(), nullable=False),
    sa.Column('arrived_pence', sa.Integer(), nullable=False),
    sa.Column('arrived_on', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'LEGACY_WORKBOOK', 'BANK_CSV', 'CSV_UPLOAD', name='financesource', native_enum=False), nullable=False),
    sa.Column('source_ref', sa.String(length=400), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint('arrived_pence >= 0', name=op.f('ck_card_payout_arrived_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_payout')),
    sa.UniqueConstraint('sold_on', name=op.f('uq_card_payout_sold_on'))
    )
    op.create_table('cash_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('counted_pence', sa.Integer(), nullable=False),
    sa.Column('counted_by', sa.String(length=120), nullable=False),
    sa.Column('counted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explained_by', sa.String(length=120), nullable=True),
    sa.Column('explained_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'LEGACY_WORKBOOK', 'BANK_CSV', 'CSV_UPLOAD', name='financesource', native_enum=False), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('counted_pence >= 0', name=op.f('ck_cash_count_counted_non_negative')),
    sa.CheckConstraint('explanation IS NULL OR (explained_by IS NOT NULL AND explained_at IS NOT NULL)', name=op.f('ck_cash_count_explanation_signed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_count')),
    sa.UniqueConstraint('business_date', name=op.f('uq_cash_count_business_date'))
    )
    op.create_table('channel_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('DELIVEROO', 'JUST_EAT', name='saleschannelname', native_enum=False), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('gross_pence', sa.Integer(), nullable=True),
    sa.Column('commission_pence', sa.Integer(), nullable=True),
    sa.Column('ad_spend_pence', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('CSV_UPLOAD', 'BROWSER_AGENT', 'PARTNER_API', 'MANUAL', 'LEGACY_WORKBOOK', name='channelsourcekind', native_enum=False), nullable=False),
    sa.Column('source_ref', sa.String(length=400), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint('ad_spend_pence IS NULL OR ad_spend_pence >= 0', name=op.f('ck_channel_statement_ad_spend_non_negative')),
    sa.CheckConstraint('commission_pence IS NULL OR commission_pence >= 0', name=op.f('ck_channel_statement_commission_non_negative')),
    sa.CheckConstraint('gross_pence IS NULL OR gross_pence >= 0', name=op.f('ck_channel_statement_gross_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_statement')),
    sa.UniqueConstraint('channel', 'month', name='uq_channel_statement_channel_month')
    )
    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('expense_group', sa.Enum('COGS', 'OPEX', name='expensegroup', native_enum=False), nullable=False),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_category')),
    sa.UniqueConstraint('name', name=op.f('uq_expense_category_name'))
    )
    op.create_table('finance_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_lag_working_days', sa.Integer(), server_default='2', nullable=False),
    sa.Column('card_fee_bp', sa.Integer(), server_default='175', nullable=False),
    sa.Column('cash_tolerance_pence', sa.Integer(), server_default='500', nullable=False),
    sa.Column('payout_tolerance_pence', sa.Integer(), server_default='100', nullable=False),
    sa.Column('stock_pct_threshold_bp', sa.Integer(), server_default='3200', nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint('card_fee_bp BETWEEN 0 AND 1000', name=op.f('ck_finance_setting_card_fee_range')),
    sa.CheckConstraint('cash_tolerance_pence >= 0', name=op.f('ck_finance_setting_cash_tolerance_non_negative')),
    sa.CheckConstraint('id = 1', name=op.f('ck_finance_setting_single_row')),
    sa.CheckConstraint('payout_lag_working_days BETWEEN 0 AND 10', name=op.f('ck_finance_setting_payout_lag_range')),
    sa.CheckConstraint('payout_tolerance_pence >= 0', name=op.f('ck_finance_setting_payout_tolerance_non_negative')),
    sa.CheckConstraint('stock_pct_threshold_bp BETWEEN 0 AND 10000', name=op.f('ck_finance_setting_stock_pct_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_setting'))
    )
    op.create_table('media_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint("content_type IN ('image/webp', 'image/jpeg', 'image/png')", name=op.f('ck_media_asset_image_type')),
    sa.CheckConstraint('bytes > 0 AND bytes <= 2097152', name=op.f('ck_media_asset_size_limit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_asset')),
    sa.UniqueConstraint('sha256', name=op.f('uq_media_asset_sha256'))
    )
    op.create_table('menu_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('DRINKS', 'FOOD', 'OTHER', name='menukind', native_enum=False), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_category')),
    sa.UniqueConstraint('name', name=op.f('uq_menu_category_name'))
    )
    op.create_table('sync_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Enum('SCHEDULED', 'MANUAL_WEB', 'CLI', name='synctrigger', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('LIVE', 'FIXTURES', name='syncsource', native_enum=False), nullable=False),
    sa.Column('started_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'OK', 'PARTIAL', 'SKIPPED', 'FAILED', name='syncstatus', native_enum=False), nullable=False),
    sa.Column('window_since', sa.Date(), nullable=False),
    sa.Column('window_until', sa.Date(), nullable=False),
    sa.Column('receipts_seen', sa.Integer(), nullable=True),
    sa.Column('lines_ingested', sa.Integer(), nullable=True),
    sa.Column('unresolved_count', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint("(status = 'RUNNING') = (finished_at IS NULL)", name=op.f('ck_sync_run_finished_iff_not_running')),
    sa.CheckConstraint('window_until >= window_since', name=op.f('ck_sync_run_window_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_run'))
    )
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.create_index('ix_sync_run_started', ['started_at'], unique=False)
        batch_op.create_index('ix_sync_run_status_started', ['status', 'started_at'], unique=False)

    op.create_table('trading_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('transactions_override', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'LEGACY_WORKBOOK', 'BANK_CSV', 'CSV_UPLOAD', name='financesource', native_enum=False), nullable=False),
    sa.Column('source_ref', sa.String(length=400), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint('transactions_override IS NULL OR transactions_override >= 0', name=op.f('ck_trading_day_transactions_override_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_day')),
    sa.UniqueConstraint('business_date', name=op.f('uq_trading_day_business_date'))
    )
    op.create_table('agent_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.Enum('WASTE_FACTOR', 'TEMPLATE_GROUPING', 'CHANNEL_IMPORT', 'DATA_FIX', 'SUPPLIER_BASKET', name='proposalkind', native_enum=False), nullable=False),
    sa.Column('subject_ref', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='proposalconfidence', native_enum=False), nullable=True),
    sa.Column('figures', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'ACCEPTED', 'DECLINED', 'SUPERSEDED', 'APPLY_FAILED', name='proposalstatus', native_enum=False), nullable=False),
    sa.Column('decided_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('applied_result', sa.JSON(), nullable=True),
    sa.CheckConstraint("status = 'WAITING' OR (decided_at IS NOT NULL AND decided_by IS NOT NULL)", name=op.f('ck_agent_proposal_decided_by_human')),
    sa.ForeignKeyConstraint(['log_id'], ['agent_action_log.id'], name=op.f('fk_agent_proposal_log_id_agent_action_log')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_proposal'))
    )
    with op.batch_alter_table('agent_proposal', schema=None) as batch_op:
        batch_op.create_index('ix_agent_proposal_run', ['run_id'], unique=False)
        batch_op.create_index('ix_agent_proposal_status', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_agent_proposal_subject', ['kind', 'subject_ref'], unique=False)

    op.create_table('auth_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('event', sa.Enum('LOGIN_OK', 'LOGIN_FAILED', 'LOGIN_RATE_LIMITED', 'SIGN_OUT', 'PASSWORD_CHANGED', 'PASSWORD_CHANGE_REFUSED', 'PASSWORD_RESET', 'SESSIONS_REVOKED', name='authevent', native_enum=False), nullable=False),
    sa.Column('via', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auth_session.id'], name=op.f('fk_auth_audit_session_id_auth_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_audit'))
    )
    with op.batch_alter_table('auth_audit', schema=None) as batch_op:
        batch_op.create_index('ix_auth_audit_at', ['at'], unique=False)
        batch_op.create_index('ix_auth_audit_event', ['event', 'at'], unique=False)

    op.create_table('ingredient_tier_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('tier_before', sa.Enum('A', 'B', 'C', name='tier', native_enum=False), nullable=False),
    sa.Column('tier_after', sa.Enum('A', 'B', 'C', name='tier', native_enum=False), nullable=False),
    sa.Column('changed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('would_clear_gate', sa.Boolean(), nullable=True),
    sa.CheckConstraint('tier_before <> tier_after', name=op.f('ck_ingredient_tier_change_tier_changes')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_ingredient_tier_change_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient_tier_change'))
    )
    with op.batch_alter_table('ingredient_tier_change', schema=None) as batch_op:
        batch_op.create_index('ix_ingredient_tier_change_ing_at', ['ingredient_id', 'changed_at'], unique=False)

    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('CARD', 'BANK_TRANSFER', 'DIRECT_DEBIT', 'STANDING_ORDER', 'CASH', 'CASH_WITHDRAWAL', 'OTHER', name='expensemethod', native_enum=False), nullable=True),
    sa.Column('kind', sa.Enum('OPERATING', 'CAPITAL', 'DRAWINGS', name='expensekind', native_enum=False), server_default='OPERATING', nullable=False),
    sa.Column('has_receipt', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'LEGACY_WORKBOOK', 'BANK_CSV', 'CSV_UPLOAD', name='financesource', native_enum=False), nullable=False),
    sa.Column('source_ref', sa.String(length=400), nullable=True),
    sa.Column('deleted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint('amount_pence > 0', name=op.f('ck_expense_amount_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], name=op.f('fk_expense_category_id_expense_category')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_expense_purchase_order_id_purchase_order')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_expense_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense'))
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index('ix_expense_kind_paid_on', ['kind', 'paid_on'], unique=False)
        batch_op.create_index('ix_expense_needs_review', ['needs_review'], unique=False)
        batch_op.create_index('ix_expense_paid_on', ['paid_on'], unique=False)
        batch_op.create_index('ix_expense_source_ref', ['source_ref'], unique=False)

    op.create_table('menu_item_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'POS_SYNC', 'LEGACY_WORKBOOK', 'BACKFILL', name='menupricesource', native_enum=False), nullable=False),
    sa.Column('set_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.CheckConstraint("source <> 'MANUAL' OR set_by IS NOT NULL", name=op.f('ck_menu_item_price_manual_price_signed')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_menu_item_price_window_ordered')),
    sa.CheckConstraint('price_pence >= 0', name=op.f('ck_menu_item_price_price_non_negative')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_menu_item_price_menu_item_id_menu_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_price'))
    )
    with op.batch_alter_table('menu_item_price', schema=None) as batch_op:
        batch_op.create_index('ix_menu_item_price_item_from', ['menu_item_id', 'effective_from'], unique=False)
        batch_op.create_index('uq_menu_item_price_one_open', ['menu_item_id'], unique=True, sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))

    op.create_table('modifier_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modifier_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('SUBSTITUTE', 'ADD', 'SCALE', name='modifieraction', native_enum=False), nullable=False),
    sa.Column('target_role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty_delta', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('qty_multiplier', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('price_is_estimate', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('changed_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_modifier_version_window_ordered')),
    sa.CheckConstraint('price_pence >= 0', name=op.f('ck_modifier_version_price_non_negative')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_modifier_version_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifier.id'], name=op.f('fk_modifier_version_modifier_id_modifier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modifier_version'))
    )
    with op.batch_alter_table('modifier_version', schema=None) as batch_op:
        batch_op.create_index('ix_modifier_version_mod_from', ['modifier_id', 'effective_from'], unique=False)
        batch_op.create_index('uq_modifier_version_one_open', ['modifier_id'], unique=True, sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))

    op.create_table('recipe_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('change_kind', sa.String(length=40), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('template_id IS NOT NULL OR menu_item_id IS NOT NULL', name=op.f('ck_recipe_change_has_subject')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_recipe_change_menu_item_id_menu_item')),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], name=op.f('fk_recipe_change_template_id_drink_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_change'))
    )
    with op.batch_alter_table('recipe_change', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_change_item', ['menu_item_id', 'effective_from'], unique=False)
        batch_op.create_index('ix_recipe_change_template', ['template_id', 'effective_from'], unique=False)

    op.create_table('director_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('CAPITAL_INJECTION', 'LOAN_TO_COMPANY', 'DRAWINGS', 'REPAYMENT', name='directorentrytype', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('in_pence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('out_pence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'LEGACY_WORKBOOK', 'BANK_CSV', 'CSV_UPLOAD', name='financesource', native_enum=False), nullable=False),
    sa.Column('source_ref', sa.String(length=400), nullable=True),
    sa.Column('deleted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint("(type IN ('CAPITAL_INJECTION', 'LOAN_TO_COMPANY') AND in_pence > 0) OR (type IN ('DRAWINGS', 'REPAYMENT') AND out_pence > 0)", name=op.f('ck_director_entry_type_matches_direction')),
    sa.CheckConstraint("expense_id IS NULL OR type = 'DRAWINGS'", name=op.f('ck_director_entry_expense_link_is_drawings')),
    sa.CheckConstraint('(in_pence > 0 AND out_pence = 0) OR (out_pence > 0 AND in_pence = 0)', name=op.f('ck_director_entry_one_direction')),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('fk_director_entry_expense_id_expense')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_director_entry')),
    sa.UniqueConstraint('expense_id', name=op.f('uq_director_entry_expense_id'))
    )
    with op.batch_alter_table('director_entry', schema=None) as batch_op:
        batch_op.create_index('ix_director_entry_date', ['entry_date'], unique=False)

    with op.batch_alter_table('agent_action_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent', sa.String(length=60), nullable=True))

    with op.batch_alter_table('channel_item_metric', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('CSV_UPLOAD', 'BROWSER_AGENT', 'PARTNER_API', 'MANUAL', 'LEGACY_WORKBOOK', name='channelsourcekind', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('channel_metric', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('CSV_UPLOAD', 'BROWSER_AGENT', 'PARTNER_API', 'MANUAL', 'LEGACY_WORKBOOK', name='channelsourcekind', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retired_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('retired_by', sa.String(length=120), nullable=True))

    with op.batch_alter_table('ingredient_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_by', sa.String(length=120), nullable=True))

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('photo_asset_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_menu_item_photo_asset_id_media_asset'), 'media_asset', ['photo_asset_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('modifier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_is_estimate', sa.Boolean(), nullable=True))

    with op.batch_alter_table('par_level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_qty_set_by', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('min_qty_set_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True))

    with op.batch_alter_table('payment_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basis', sa.Enum('TILL', 'BANK_DEPOSIT', name='paymentbasis', native_enum=False), server_default='TILL', nullable=False))
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('CASH', 'CASH_OFF_TILL', 'CARD', 'VOUCHER', 'ACCOUNT', 'OTHER', name='paymentmethod', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('CSV_UPLOAD', 'POS_API', 'MANUAL', 'LEGACY_WORKBOOK', name='paymentsourcekind', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_by', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('receipt_asset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receipt_uploaded_by', sa.String(length=120), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_purchase_order_receipt_asset_id_media_asset'), 'media_asset', ['receipt_asset_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stock_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_source', sa.Enum('ENTERED', 'ASSUMED', name='expirysource', native_enum=False), nullable=True))
        batch_op.add_column(sa.Column('received_by', sa.String(length=120), nullable=True))

    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_code', sa.Enum('WENT_OFF', 'SPILLED', 'STAFF', 'OTHER', name='writeoffreason', native_enum=False), nullable=True))
        batch_op.add_column(sa.Column('recorded_by', sa.String(length=120), nullable=True))

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('archived_by', sa.String(length=120), nullable=True))

    with op.batch_alter_table('supplier_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('archived_by', sa.String(length=120), nullable=True))

    with op.batch_alter_table('tesco_routing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailer', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('bought_by', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('paid_pence', sa.Integer(), nullable=True))

    # ### end Alembic commands ###

    # --- CHECKs on existing tables (autogenerate does not compare them) -------------
    op.execute(
        "UPDATE purchase_order SET cancelled_at = created_at, "
        "cancelled_by = '(not recorded)' "
        "WHERE status = 'CANCELLED' AND (cancelled_at IS NULL OR cancelled_by IS NULL)"
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_check_constraint(
            op.f('ck_purchase_order_cancelled_requires_human'),
            "(status <> 'CANCELLED') OR (cancelled_by IS NOT NULL AND cancelled_at IS NOT NULL)",
        )
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.create_check_constraint(
            op.f('ck_stock_movement_reason_matches_type'),
            "reason_code IS NULL "
            "OR (type = 'STAFF' AND reason_code = 'STAFF') "
            "OR (type = 'WASTE' AND reason_code IN ('WENT_OFF', 'SPILLED', 'OTHER'))",
        )
        batch_op.create_check_constraint(
            op.f('ck_stock_movement_write_off_signed'),
            "reason_code IS NULL OR recorded_by IS NOT NULL",
        )
        batch_op.create_check_constraint(
            op.f('ck_stock_movement_other_needs_note'),
            "reason_code <> 'OTHER' OR note IS NOT NULL",
        )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_check_constraint(
            op.f('ck_supplier_archive_signed'), "archived_at IS NULL OR archived_by IS NOT NULL"
        )
    with op.batch_alter_table('supplier_product', schema=None) as batch_op:
        batch_op.create_check_constraint(
            op.f('ck_supplier_product_archive_signed'),
            "archived_at IS NULL OR archived_by IS NOT NULL",
        )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_check_constraint(
            op.f('ck_ingredient_retire_signed'), "retired_at IS NULL OR retired_by IS NOT NULL"
        )

    # --- reference data --------------------------------------------------------------
    category = sa.table(
        'expense_category',
        sa.column('name', sa.String),
        sa.column('expense_group', sa.String),
        sa.column('sort', sa.Integer),
        sa.column('is_active', sa.Boolean),
    )
    op.bulk_insert(
        category,
        [
            {'name': name, 'expense_group': group, 'sort': i, 'is_active': True}
            for i, (name, group) in enumerate(EXPENSE_CATEGORIES, start=1)
        ],
    )
    setting = sa.table(
        'finance_setting',
        sa.column('id', sa.Integer),
        sa.column('payout_lag_working_days', sa.Integer),
        sa.column('card_fee_bp', sa.Integer),
        sa.column('cash_tolerance_pence', sa.Integer),
        sa.column('payout_tolerance_pence', sa.Integer),
        sa.column('stock_pct_threshold_bp', sa.Integer),
        sa.column('updated_at', cafeops.db.types.UTCDateTime()),
    )
    op.bulk_insert(
        setting,
        [
            {
                'id': 1,
                'payout_lag_working_days': 2,
                'card_fee_bp': 175,
                'cash_tolerance_pence': 500,
                'payout_tolerance_pence': 100,
                'stock_pct_threshold_bp': 3200,
                'updated_at': datetime.now(UTC),
            }
        ],
    )

    # --- backfills -------------------------------------------------------------------
    bind = op.get_bind()
    utc = cafeops.db.types.UTCDateTime()
    sale = sa.table('sale', sa.column('sold_at', utc))
    earliest = bind.execute(sa.select(sa.func.min(sale.c.sold_at))).scalar()
    history_starts = earliest if earliest is not None else datetime.now(UTC)
    starts = sa.literal(history_starts, utc)

    menu_item = sa.table('menu_item', sa.column('id', sa.Integer), sa.column('price_pence', sa.Integer))
    menu_item_price = sa.table(
        'menu_item_price',
        sa.column('menu_item_id', sa.Integer),
        sa.column('price_pence', sa.Integer),
        sa.column('effective_from', utc),
        sa.column('source', sa.String),
        sa.column('note', sa.String),
    )
    op.execute(
        sa.insert(menu_item_price).from_select(
            ['menu_item_id', 'price_pence', 'effective_from', 'source', 'note'],
            sa.select(
                menu_item.c.id,
                menu_item.c.price_pence,
                starts,
                sa.literal('BACKFILL'),
                sa.literal(f'carried from menu_item.price_pence by migration {revision}'),
            ),
        )
    )

    # Qty columns copy as raw stored values: both sides are the same Qty type, so the
    # copy is exact on every backend without a Python round-trip.
    mod_cols = [
        'action', 'target_role', 'ingredient_id', 'qty_delta', 'qty_multiplier',
        'price_pence', 'is_active',
    ]
    modifier = sa.table('modifier', sa.column('id', sa.Integer), *[sa.column(c) for c in mod_cols])
    modifier_version = sa.table(
        'modifier_version',
        sa.column('modifier_id', sa.Integer),
        sa.column('effective_from', utc),
        *[sa.column(c) for c in mod_cols],
    )
    op.execute(
        sa.insert(modifier_version).from_select(
            ['modifier_id', *mod_cols, 'effective_from'],
            sa.select(modifier.c.id, *[modifier.c[c] for c in mod_cols], starts),
        )
    )

    op.execute(
        "UPDATE stock_batch SET expiry_source = 'ASSUMED' WHERE note LIKE 'EXPIRY ASSUMED%'"
    )


def _refuse_if_used(sql: str, what: str) -> None:
    count = op.get_bind().execute(sa.text(sql)).scalar()
    if count:
        raise RuntimeError(
            f"refusing to downgrade {revision}: {count} row(s) use {what}, which the "
            "previous schema cannot represent. Move or delete them first."
        )


def downgrade() -> None:
    """Downgrade schema."""
    _refuse_if_used(
        "SELECT COUNT(*) FROM payment_day WHERE method = 'CASH_OFF_TILL'",
        "payment_day.method = CASH_OFF_TILL",
    )
    _refuse_if_used(
        "SELECT COUNT(*) FROM payment_day WHERE source = 'LEGACY_WORKBOOK'",
        "payment_day.source = LEGACY_WORKBOOK",
    )
    _refuse_if_used(
        "SELECT COUNT(*) FROM payment_day WHERE basis <> 'TILL'",
        "payment_day.basis = BANK_DEPOSIT",
    )
    _refuse_if_used(
        "SELECT (SELECT COUNT(*) FROM channel_metric WHERE source = 'LEGACY_WORKBOOK')"
        " + (SELECT COUNT(*) FROM channel_item_metric WHERE source = 'LEGACY_WORKBOOK')",
        "channel source LEGACY_WORKBOOK",
    )
    _refuse_if_used(
        "SELECT COUNT(*) FROM stock_movement WHERE reason_code IS NOT NULL",
        "stock_movement.reason_code (write-off reasons would be lost)",
    )

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_ingredient_retire_signed'), type_='check')
    with op.batch_alter_table('supplier_product', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_supplier_product_archive_signed'), type_='check')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_supplier_archive_signed'), type_='check')
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_stock_movement_other_needs_note'), type_='check')
        batch_op.drop_constraint(op.f('ck_stock_movement_write_off_signed'), type_='check')
        batch_op.drop_constraint(op.f('ck_stock_movement_reason_matches_type'), type_='check')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_purchase_order_cancelled_requires_human'), type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesco_routing', schema=None) as batch_op:
        batch_op.drop_column('paid_pence')
        batch_op.drop_column('bought_by')
        batch_op.drop_column('retailer')

    with op.batch_alter_table('supplier_product', schema=None) as batch_op:
        batch_op.drop_column('archived_by')
        batch_op.drop_column('archived_at')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('archived_by')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('kind')

    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_column('recorded_by')
        batch_op.drop_column('reason_code')

    with op.batch_alter_table('stock_batch', schema=None) as batch_op:
        batch_op.drop_column('received_by')
        batch_op.drop_column('expiry_source')

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_order_receipt_asset_id_media_asset'), type_='foreignkey')
        batch_op.drop_column('receipt_uploaded_by')
        batch_op.drop_column('receipt_asset_id')
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('sent_by')

    with op.batch_alter_table('payment_day', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Enum('CSV_UPLOAD', 'POS_API', 'MANUAL', 'LEGACY_WORKBOOK', name='paymentsourcekind', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.Enum('CASH', 'CASH_OFF_TILL', 'CARD', 'VOUCHER', 'ACCOUNT', 'OTHER', name='paymentmethod', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('basis')

    with op.batch_alter_table('par_level', schema=None) as batch_op:
        batch_op.drop_column('min_qty_set_at')
        batch_op.drop_column('min_qty_set_by')

    with op.batch_alter_table('modifier', schema=None) as batch_op:
        batch_op.drop_column('price_is_estimate')

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_menu_item_photo_asset_id_media_asset'), type_='foreignkey')
        batch_op.drop_column('photo_asset_id')
        batch_op.drop_column('note')

    with op.batch_alter_table('ingredient_price', schema=None) as batch_op:
        batch_op.drop_column('recorded_by')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('retired_by')
        batch_op.drop_column('retired_at')

    with op.batch_alter_table('channel_metric', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Enum('CSV_UPLOAD', 'BROWSER_AGENT', 'PARTNER_API', 'MANUAL', 'LEGACY_WORKBOOK', name='channelsourcekind', native_enum=False),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    with op.batch_alter_table('channel_item_metric', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Enum('CSV_UPLOAD', 'BROWSER_AGENT', 'PARTNER_API', 'MANUAL', 'LEGACY_WORKBOOK', name='channelsourcekind', native_enum=False),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    with op.batch_alter_table('agent_action_log', schema=None) as batch_op:
        batch_op.drop_column('agent')

    with op.batch_alter_table('director_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_director_entry_date')

    op.drop_table('director_entry')
    with op.batch_alter_table('recipe_change', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_change_template')
        batch_op.drop_index('ix_recipe_change_item')

    op.drop_table('recipe_change')
    with op.batch_alter_table('modifier_version', schema=None) as batch_op:
        batch_op.drop_index('uq_modifier_version_one_open', sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))
        batch_op.drop_index('ix_modifier_version_mod_from')

    op.drop_table('modifier_version')
    with op.batch_alter_table('menu_item_price', schema=None) as batch_op:
        batch_op.drop_index('uq_menu_item_price_one_open', sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))
        batch_op.drop_index('ix_menu_item_price_item_from')

    op.drop_table('menu_item_price')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index('ix_expense_source_ref')
        batch_op.drop_index('ix_expense_paid_on')
        batch_op.drop_index('ix_expense_needs_review')
        batch_op.drop_index('ix_expense_kind_paid_on')

    op.drop_table('expense')
    with op.batch_alter_table('ingredient_tier_change', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredient_tier_change_ing_at')

    op.drop_table('ingredient_tier_change')
    with op.batch_alter_table('auth_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_audit_event')
        batch_op.drop_index('ix_auth_audit_at')

    op.drop_table('auth_audit')
    with op.batch_alter_table('agent_proposal', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_proposal_subject')
        batch_op.drop_index('ix_agent_proposal_status')
        batch_op.drop_index('ix_agent_proposal_run')

    op.drop_table('agent_proposal')
    op.drop_table('trading_day')
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_run_status_started')
        batch_op.drop_index('ix_sync_run_started')

    op.drop_table('sync_run')
    op.drop_table('menu_category')
    op.drop_table('media_asset')
    op.drop_table('finance_setting')
    op.drop_table('expense_category')
    op.drop_table('channel_statement')
    op.drop_table('cash_count')
    op.drop_table('card_payout')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_session_active')

    op.drop_table('auth_session')
    op.drop_table('auth_credential')
    # ### end Alembic commands ###
