"""initial schema v2

Revision ID: a73b90bd6cb4
Revises: 
Create Date: 2026-09-19 15:23:08.514468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cafeops.db.types  # custom column types (Qty, UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = 'a73b90bd6cb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('OK', 'REFUSED', 'FAILED', 'AWAITING_HUMAN', name='agenttooloutcome', native_enum=False), nullable=False),
    sa.Column('refusal_reason', sa.String(length=400), nullable=True),
    sa.Column('proposal_ref', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_action_log'))
    )
    with op.batch_alter_table('agent_action_log', schema=None) as batch_op:
        batch_op.create_index('ix_agent_log_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_agent_log_outcome', ['outcome'], unique=False)
        batch_op.create_index('ix_agent_log_run', ['run_id'], unique=False)

    op.create_table('channel_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('DELIVEROO', 'JUST_EAT', name='saleschannelname', native_enum=False), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('menu_views', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('ad_spend_pence', sa.Integer(), nullable=True),
    sa.Column('attributed_revenue_pence', sa.Integer(), nullable=True),
    sa.Column('commission_pence', sa.Integer(), nullable=True),
    sa.Column('gross_pence', sa.Integer(), nullable=True),
    sa.Column('avg_position_bp', sa.Integer(), nullable=True),
    sa.Column('rating_bp', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('CSV_UPLOAD', 'BROWSER_AGENT', 'PARTNER_API', 'MANUAL', name='channelsourcekind', native_enum=False), nullable=False),
    sa.Column('ingested_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source_ref', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_metric')),
    sa.UniqueConstraint('channel', 'metric_date', name='uq_channel_metric_day')
    )
    with op.batch_alter_table('channel_metric', schema=None) as batch_op:
        batch_op.create_index('ix_channel_metric_date', ['metric_date'], unique=False)

    op.create_table('drink_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('prep_seconds_by_size', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drink_template')),
    sa.UniqueConstraint('name', name=op.f('uq_drink_template_name'))
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.Enum('L', 'KG', 'ML', 'G', 'EACH', name='unit', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('tier', sa.Enum('A', 'B', 'C', name='tier', native_enum=False), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('waste_factor', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('current_cost_pence_per_unit', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('current_cost_source', sa.Enum('INVOICE', 'ESTIMATE', 'SUPPLIER_FEED', name='pricesource', native_enum=False), nullable=True),
    sa.Column('storage', sa.Enum('AMBIENT', 'CHILLED', 'FROZEN', name='storage', native_enum=False), server_default='AMBIENT', nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('open_life_days', sa.Integer(), nullable=True),
    sa.Column('transit_buffer_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shelf_life_source', sa.Enum('INVOICE', 'ESTIMATE', 'SUPPLIER_FEED', name='pricesource', native_enum=False), nullable=True),
    sa.Column('source_note', sa.String(length=400), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient')),
    sa.UniqueConstraint('name', name=op.f('uq_ingredient_name'))
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_recurring_annually', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season')),
    sa.UniqueConstraint('name', name=op.f('uq_season_name'))
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('delivery_weekdays', sa.JSON(), nullable=False),
    sa.Column('min_order_pence', sa.Integer(), nullable=False),
    sa.Column('order_channel', sa.Enum('PORTAL', 'EMAIL', 'EDI', 'MANUAL', 'BROWSER_AGENT', name='orderchannel', native_enum=False), nullable=False),
    sa.Column('contact', sa.String(length=400), nullable=True),
    sa.Column('cutoff_time', sa.Time(), nullable=True),
    sa.Column('delivery_fee_pence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('free_delivery_threshold_pence', sa.Integer(), nullable=True),
    sa.Column('terms_are_placeholders', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('order_url', sa.String(length=500), nullable=True),
    sa.Column('agent_instructions', sa.Text(), nullable=True),
    sa.Column('channel_config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier')),
    sa.UniqueConstraint('name', name=op.f('uq_supplier_name'))
    )
    op.create_table('checklist_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OK', 'LOW', name='checkliststatus', native_enum=False), nullable=False),
    sa.Column('responded_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('responded_by', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_checklist_response_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_response'))
    )
    with op.batch_alter_table('checklist_response', schema=None) as batch_op:
        batch_op.create_index('ix_checklist_ing_at', ['ingredient_id', 'responded_at'], unique=False)

    op.create_table('ingredient_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('pack_size', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('pack_unit', sa.Enum('L', 'KG', 'ML', 'G', 'EACH', name='unit', native_enum=False), nullable=False),
    sa.Column('pack_cost_pence', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit_pence', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('INVOICE', 'ESTIMATE', 'SUPPLIER_FEED', name='pricesource', native_enum=False), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_ingredient_price_ingredient_id_ingredient'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_ingredient_price_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient_price'))
    )
    with op.batch_alter_table('ingredient_price', schema=None) as batch_op:
        batch_op.create_index('ix_ingredient_price_ing_from', ['ingredient_id', 'effective_from'], unique=False)

    op.create_table('legacy_staged_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_no', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('size_code', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('sell_price_pence', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=160), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('raw_unit', sa.String(length=40), nullable=True),
    sa.Column('role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=True),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('data_quality_flag', sa.String(length=200), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_legacy_staged_recipe_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_staged_recipe'))
    )
    with op.batch_alter_table('legacy_staged_recipe', schema=None) as batch_op:
        batch_op.create_index('ix_staged_item', ['item_name', 'size_code'], unique=False)
        batch_op.create_index('ix_staged_recipe_no', ['recipe_no'], unique=False)

    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lightspeed_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('size_code', sa.Enum('S', 'M', 'XL', 'ONE', name='sizecode', native_enum=False), nullable=True),
    sa.Column('selected_options', sa.JSON(), nullable=False),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('manual_recipe', sa.Boolean(), nullable=False),
    sa.Column('prep_seconds', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('data_quality_flag', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('fk_menu_item_season_id_season')),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], name=op.f('fk_menu_item_template_id_drink_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item')),
    sa.UniqueConstraint('lightspeed_id', name=op.f('uq_menu_item_lightspeed_id')),
    sa.UniqueConstraint('name', 'size_code', name='uq_menu_item_name_size')
    )
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.create_index('ix_menu_item_template', ['template_id', 'size_code'], unique=False)

    op.create_table('modifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('lightspeed_modifier_id', sa.String(length=80), nullable=True),
    sa.Column('action', sa.Enum('SUBSTITUTE', 'ADD', 'SCALE', name='modifieraction', native_enum=False), nullable=False),
    sa.Column('target_role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty_delta', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('qty_multiplier', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_modifier_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modifier')),
    sa.UniqueConstraint('lightspeed_modifier_id', name=op.f('uq_modifier_lightspeed_modifier_id')),
    sa.UniqueConstraint('name', name=op.f('uq_modifier_name'))
    )
    op.create_table('par_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('safety_days', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('min_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('max_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('auto_order_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_order_granted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('auto_order_revoked_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('auto_order_reason', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_par_level_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_par_level')),
    sa.UniqueConstraint('ingredient_id', name=op.f('uq_par_level_ingredient_id'))
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_CONFIRM', 'CONFIRMED', 'SENT', 'RECEIVED', 'CANCELLED', name='postatus', native_enum=False), nullable=False),
    sa.Column('target_delivery_date', sa.Date(), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=120), nullable=True),
    sa.Column('sent_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('total_pence', sa.Integer(), nullable=False),
    sa.Column('min_order_topped_up', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('routing_reason', sa.Text(), nullable=True),
    sa.Column('delivery_fee_pence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confidence_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("(status <> 'SENT') OR (sent_at IS NOT NULL)", name=op.f('ck_purchase_order_ck_po_sent_requires_sent_at')),
    sa.CheckConstraint("(status NOT IN ('CONFIRMED', 'SENT', 'RECEIVED')) OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)", name=op.f('ck_purchase_order_ck_po_confirmed_requires_human')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_purchase_order_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order'))
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index('ix_po_supplier_status', ['supplier_id', 'status'], unique=False)
        batch_op.create_index('ix_po_target_delivery', ['target_delivery_date'], unique=False)

    op.create_table('size_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('S', 'M', 'XL', 'ONE', name='sizecode', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], name=op.f('fk_size_profile_template_id_drink_template'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_size_profile')),
    sa.UniqueConstraint('template_id', 'code', name='uq_size_profile_tpl_code')
    )
    op.create_table('stock_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('counted_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('counted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('counted_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_stock_count_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_count'))
    )
    with op.batch_alter_table('stock_count', schema=None) as batch_op:
        batch_op.create_index('ix_stock_count_ing_at', ['ingredient_id', 'counted_at'], unique=False)

    op.create_table('supplier_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('pack_size', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('pack_unit', sa.Enum('L', 'KG', 'ML', 'G', 'EACH', name='unit', native_enum=False), nullable=False),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('moq_packs', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_seen_price_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_supplier_product_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_product_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_product')),
    sa.UniqueConstraint('supplier_id', 'ingredient_id', 'sku', name='uq_supplier_product_sup_ing_sku')
    )
    op.create_table('template_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty_by_size', sa.JSON(), nullable=False),
    sa.Column('is_substitutable', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_template_component_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['template_component.id'], name=op.f('fk_template_component_superseded_by_id_template_component'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], name=op.f('fk_template_component_template_id_drink_template'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_component'))
    )
    with op.batch_alter_table('template_component', schema=None) as batch_op:
        batch_op.create_index('ix_template_component_role', ['template_id', 'role'], unique=False)
        batch_op.create_index('ix_template_component_tpl_from', ['template_id', 'effective_from'], unique=False)

    op.create_table('variant_axis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], name=op.f('fk_variant_axis_template_id_drink_template'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant_axis')),
    sa.UniqueConstraint('template_id', 'name', name='uq_variant_axis_tpl_name')
    )
    op.create_table('channel_item_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('DELIVEROO', 'JUST_EAT', name='saleschannelname', native_enum=False), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('revenue_pence', sa.Integer(), nullable=True),
    sa.Column('rank_in_category', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('CSV_UPLOAD', 'BROWSER_AGENT', 'PARTNER_API', 'MANUAL', name='channelsourcekind', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_channel_item_metric_menu_item_id_menu_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_item_metric')),
    sa.UniqueConstraint('channel', 'metric_date', 'menu_item_id', name='uq_channel_item_metric_day')
    )
    with op.batch_alter_table('channel_item_metric', schema=None) as batch_op:
        batch_op.create_index('ix_channel_item_metric_item', ['menu_item_id', 'metric_date'], unique=False)

    op.create_table('drift_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('stock_count_id', sa.Integer(), nullable=False),
    sa.Column('theoretical_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('counted_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('drift_pct', sa.Float(), nullable=False),
    sa.Column('waste_factor_at_count', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('expired_qty_in_window', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('observed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_drift_observation_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['stock_count_id'], ['stock_count.id'], name=op.f('fk_drift_observation_stock_count_id_stock_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drift_observation'))
    )
    with op.batch_alter_table('drift_observation', schema=None) as batch_op:
        batch_op.create_index('ix_drift_ing_at', ['ingredient_id', 'observed_at'], unique=False)

    op.create_table('manual_recipe_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_manual_recipe_line_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_manual_recipe_line_menu_item_id_menu_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_recipe_line'))
    )
    with op.batch_alter_table('manual_recipe_line', schema=None) as batch_op:
        batch_op.create_index('ix_manual_recipe_item_from', ['menu_item_id', 'effective_from'], unique=False)

    op.create_table('menu_item_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('cost_pence', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('cost_source', sa.Enum('INVOICE', 'ESTIMATE', 'SUPPLIER_FEED', name='pricesource', native_enum=False), nullable=True),
    sa.Column('has_missing_cost', sa.Boolean(), nullable=False),
    sa.Column('ingredient_count', sa.Integer(), nullable=False),
    sa.Column('labour_cost_pence', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('prep_seconds', sa.Integer(), nullable=True),
    sa.Column('loaded_hourly_rate_pence', sa.Integer(), nullable=True),
    sa.Column('computed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_menu_item_cost_menu_item_id_menu_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_cost')),
    sa.UniqueConstraint('menu_item_id', name=op.f('uq_menu_item_cost_menu_item_id'))
    )
    op.create_table('po_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Integer(), nullable=False),
    sa.Column('suggested_packs', sa.Integer(), nullable=False),
    sa.Column('final_packs', sa.Integer(), nullable=False),
    sa.Column('unit_price_pence', sa.Integer(), nullable=False),
    sa.Column('received_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('received_expires_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('need_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('is_top_up', sa.Boolean(), nullable=False),
    sa.Column('cap_reason', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_po_line_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], name=op.f('fk_po_line_po_id_purchase_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_product.id'], name=op.f('fk_po_line_supplier_product_id_supplier_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_line'))
    )
    with op.batch_alter_table('po_line', schema=None) as batch_op:
        batch_op.create_index('ix_po_line_po', ['po_id'], unique=False)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lightspeed_receipt_id', sa.String(length=80), nullable=False),
    sa.Column('lightspeed_line_id', sa.String(length=80), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('gross_pence', sa.Integer(), nullable=False),
    sa.Column('sold_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.Enum('EPOS', 'DELIVEROO', 'JUST_EAT', 'OTHER', name='salechannel', native_enum=False), nullable=False),
    sa.Column('applied_modifiers', sa.JSON(), nullable=False),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('expanded_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_sale_menu_item_id_menu_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale')),
    sa.UniqueConstraint('lightspeed_line_id', name=op.f('uq_sale_lightspeed_line_id'))
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index('ix_sale_expanded_at', ['expanded_at'], unique=False)
        batch_op.create_index('ix_sale_receipt', ['lightspeed_receipt_id'], unique=False)
        batch_op.create_index('ix_sale_sold_at', ['sold_at'], unique=False)

    op.create_table('variant_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty_by_size', sa.JSON(), nullable=True),
    sa.Column('price_delta_pence', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['axis_id'], ['variant_axis.id'], name=op.f('fk_variant_option_axis_id_variant_axis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_variant_option_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('fk_variant_option_season_id_season')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant_option')),
    sa.UniqueConstraint('axis_id', 'name', 'effective_from', name='uq_variant_option_axis_name')
    )
    with op.batch_alter_table('variant_option', schema=None) as batch_op:
        batch_op.create_index('ix_variant_option_axis_from', ['axis_id', 'effective_from'], unique=False)

    op.create_table('stock_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.Column('qty_received', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('qty_remaining', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('received_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('opened_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('unit_cost_pence', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('expired_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_stock_batch_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_line.id'], name=op.f('fk_stock_batch_po_line_id_po_line')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_batch'))
    )
    with op.batch_alter_table('stock_batch', schema=None) as batch_op:
        batch_op.create_index('ix_stock_batch_ing_expires', ['ingredient_id', 'expires_at'], unique=False)
        batch_op.create_index('ix_stock_batch_open', ['ingredient_id', 'expired_at'], unique=False)
        batch_op.create_index('ix_stock_batch_po_line', ['po_line_id'], unique=False)

    op.create_table('tesco_routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=False),
    sa.Column('retail_unit_price_pence', sa.Integer(), nullable=True),
    sa.Column('preferred_unit_price_pence', sa.Integer(), nullable=True),
    sa.Column('premium_pence', sa.Integer(), nullable=True),
    sa.Column('would_be_supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_tesco_routing_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_line.id'], name=op.f('fk_tesco_routing_po_line_id_po_line')),
    sa.ForeignKeyConstraint(['would_be_supplier_id'], ['supplier.id'], name=op.f('fk_tesco_routing_would_be_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tesco_routing'))
    )
    with op.batch_alter_table('tesco_routing', schema=None) as batch_op:
        batch_op.create_index('ix_tesco_routing_at', ['occurred_at'], unique=False)

    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('SALE', 'DELIVERY', 'WASTE', 'ADJUSTMENT', 'STAFF', 'COUNT_RESET', 'EXPIRED', name='movementtype', native_enum=False), nullable=False),
    sa.Column('qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('occurred_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batch.id'], name=op.f('fk_stock_movement_batch_id_stock_batch')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_stock_movement_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movement'))
    )
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movement_batch', ['batch_id'], unique=False)
        batch_op.create_index('ix_stock_movement_ing_at', ['ingredient_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_stock_movement_ing_type_at', ['ingredient_id', 'type', 'occurred_at'], unique=False)
        batch_op.create_index('ix_stock_movement_ref', ['ref_type', 'ref_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movement_ref')
        batch_op.drop_index('ix_stock_movement_ing_type_at')
        batch_op.drop_index('ix_stock_movement_ing_at')
        batch_op.drop_index('ix_stock_movement_batch')

    op.drop_table('stock_movement')
    with op.batch_alter_table('tesco_routing', schema=None) as batch_op:
        batch_op.drop_index('ix_tesco_routing_at')

    op.drop_table('tesco_routing')
    with op.batch_alter_table('stock_batch', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_batch_po_line')
        batch_op.drop_index('ix_stock_batch_open')
        batch_op.drop_index('ix_stock_batch_ing_expires')

    op.drop_table('stock_batch')
    with op.batch_alter_table('variant_option', schema=None) as batch_op:
        batch_op.drop_index('ix_variant_option_axis_from')

    op.drop_table('variant_option')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index('ix_sale_sold_at')
        batch_op.drop_index('ix_sale_receipt')
        batch_op.drop_index('ix_sale_expanded_at')

    op.drop_table('sale')
    with op.batch_alter_table('po_line', schema=None) as batch_op:
        batch_op.drop_index('ix_po_line_po')

    op.drop_table('po_line')
    op.drop_table('menu_item_cost')
    with op.batch_alter_table('manual_recipe_line', schema=None) as batch_op:
        batch_op.drop_index('ix_manual_recipe_item_from')

    op.drop_table('manual_recipe_line')
    with op.batch_alter_table('drift_observation', schema=None) as batch_op:
        batch_op.drop_index('ix_drift_ing_at')

    op.drop_table('drift_observation')
    with op.batch_alter_table('channel_item_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_item_metric_item')

    op.drop_table('channel_item_metric')
    op.drop_table('variant_axis')
    with op.batch_alter_table('template_component', schema=None) as batch_op:
        batch_op.drop_index('ix_template_component_tpl_from')
        batch_op.drop_index('ix_template_component_role')

    op.drop_table('template_component')
    op.drop_table('supplier_product')
    with op.batch_alter_table('stock_count', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_count_ing_at')

    op.drop_table('stock_count')
    op.drop_table('size_profile')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index('ix_po_target_delivery')
        batch_op.drop_index('ix_po_supplier_status')

    op.drop_table('purchase_order')
    op.drop_table('par_level')
    op.drop_table('modifier')
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_item_template')

    op.drop_table('menu_item')
    with op.batch_alter_table('legacy_staged_recipe', schema=None) as batch_op:
        batch_op.drop_index('ix_staged_recipe_no')
        batch_op.drop_index('ix_staged_item')

    op.drop_table('legacy_staged_recipe')
    with op.batch_alter_table('ingredient_price', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredient_price_ing_from')

    op.drop_table('ingredient_price')
    with op.batch_alter_table('checklist_response', schema=None) as batch_op:
        batch_op.drop_index('ix_checklist_ing_at')

    op.drop_table('checklist_response')
    op.drop_table('supplier')
    op.drop_table('season')
    op.drop_table('ingredient')
    op.drop_table('drink_template')
    with op.batch_alter_table('channel_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_metric_date')

    op.drop_table('channel_metric')
    with op.batch_alter_table('agent_action_log', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_log_run')
        batch_op.drop_index('ix_agent_log_outcome')
        batch_op.drop_index('ix_agent_log_at')

    op.drop_table('agent_action_log')
    # ### end Alembic commands ###
