"""loyalty: Sasha's Corner Rewards and the staff who stamp it

docs/loyalty/CONTRACT.md §2. All new tables, so no batch rebuild of anything that exists:
staff_user, staff_device, staff_session; loyalty_program, loyalty_member, loyalty_card,
loyalty_stamp_event, loyalty_reward, loyalty_otp, loyalty_campaign,
loyalty_campaign_delivery, wallet_push_outbox, loyalty_audit.

Autogenerate also proposed re-creating purchase_order's receipt_asset_id foreign key
(an unnamed constraint in an older revision). That is unrelated drift and was removed:
this revision touches loyalty tables only.

Reference data: the one programme the café runs today (`slug = "stamp"`, 8 stamps, any
drink), so the join page works the moment the schema exists. Its fields are editable
from the back office; nothing else is seeded -- no members, no staff.

Revision ID: b7c1e0a10001
Revises: 62aa94a23687
Create Date: 2026-09-28 12:36:05.962512

"""
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cafeops.db.types  # custom column types (Qty, UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = 'b7c1e0a10001'
down_revision: Union[str, Sequence[str], None] = '62aa94a23687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('segment', sa.Enum('ALL_OPTED_IN', 'LAPSED_30', 'REWARD_READY', 'NEW_30', name='campaignsegment', native_enum=False), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sent_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('recipients', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_campaign'))
    )
    op.create_table('loyalty_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birthday_day', sa.Integer(), nullable=True),
    sa.Column('birthday_month', sa.Integer(), nullable=True),
    sa.Column('birthday_set_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('opt_in_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('opt_in_source', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('referred_by_member_id', sa.Integer(), nullable=True),
    sa.Column('referral_rewarded_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('terms_accepted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(birthday_day IS NULL) = (birthday_month IS NULL)', name=op.f('ck_loyalty_member_birthday_complete')),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL OR deleted_at IS NOT NULL', name=op.f('ck_loyalty_member_has_contact')),
    sa.ForeignKeyConstraint(['referred_by_member_id'], ['loyalty_member.id'], name=op.f('fk_loyalty_member_referred_by_member_id_loyalty_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_member')),
    sa.UniqueConstraint('email', name=op.f('uq_loyalty_member_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_loyalty_member_phone'))
    )
    with op.batch_alter_table('loyalty_member', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_member_activity', ['last_activity_at'], unique=False)
        batch_op.create_index('ix_loyalty_member_created', ['created_at'], unique=False)

    op.create_table('loyalty_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('stamps_required', sa.Integer(), nullable=False),
    sa.Column('max_stamps_per_scan', sa.Integer(), nullable=False),
    sa.Column('reward_text', sa.String(length=120), nullable=False),
    sa.Column('reward_max_price_pence', sa.Integer(), nullable=True),
    sa.Column('birthday_reward', sa.Boolean(), nullable=False),
    sa.Column('referral_stamps', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_stamps_per_scan >= 1', name=op.f('ck_loyalty_program_max_per_scan_positive')),
    sa.CheckConstraint('referral_stamps >= 0', name=op.f('ck_loyalty_program_referral_stamps_non_negative')),
    sa.CheckConstraint('stamps_required >= 1', name=op.f('ck_loyalty_program_stamps_required_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_program')),
    sa.UniqueConstraint('slug', name=op.f('uq_loyalty_program_slug'))
    )
    op.create_table('staff_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('pairing_code_hash', sa.String(length=64), nullable=True),
    sa.Column('pairing_expires_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('registered_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_device')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_staff_device_token_hash'))
    )
    with op.batch_alter_table('staff_device', schema=None) as batch_op:
        batch_op.create_index('ix_staff_device_pairing', ['pairing_code_hash'], unique=False)

    op.create_table('staff_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('STAFF', 'MANAGER', 'OWNER', name='staffrole', native_enum=False), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_user')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_staff_user_telegram_id'))
    )
    op.create_table('loyalty_campaign_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('sent_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('returned_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['loyalty_campaign.id'], name=op.f('fk_loyalty_campaign_delivery_campaign_id_loyalty_campaign')),
    sa.ForeignKeyConstraint(['member_id'], ['loyalty_member.id'], name=op.f('fk_loyalty_campaign_delivery_member_id_loyalty_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_campaign_delivery')),
    sa.UniqueConstraint('campaign_id', 'member_id', name='uq_loyalty_delivery_once')
    )
    with op.batch_alter_table('loyalty_campaign_delivery', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_delivery_member', ['member_id', 'sent_at'], unique=False)

    op.create_table('loyalty_card',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('stamps_current', sa.Integer(), nullable=False),
    sa.Column('cycles_completed', sa.Integer(), nullable=False),
    sa.Column('reward_available', sa.Boolean(), nullable=False),
    sa.Column('auth_token', sa.String(length=64), nullable=False),
    sa.Column('qr_secret', sa.String(length=32), nullable=False),
    sa.Column('web_seen_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('voided_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('stamps_current >= 0', name=op.f('ck_loyalty_card_stamps_non_negative')),
    sa.ForeignKeyConstraint(['member_id'], ['loyalty_member.id'], name=op.f('fk_loyalty_card_member_id_loyalty_member')),
    sa.ForeignKeyConstraint(['program_id'], ['loyalty_program.id'], name=op.f('fk_loyalty_card_program_id_loyalty_program')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_card')),
    sa.UniqueConstraint('auth_token', name=op.f('uq_loyalty_card_auth_token')),
    sa.UniqueConstraint('member_id', 'program_id', name='uq_loyalty_card_member_program')
    )
    with op.batch_alter_table('loyalty_card', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_card_updated', ['updated_at'], unique=False)

    op.create_table('loyalty_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'STAFF', name='otpchannel', native_enum=False), nullable=False),
    sa.Column('expires_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['loyalty_member.id'], name=op.f('fk_loyalty_otp_member_id_loyalty_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_otp'))
    )
    with op.batch_alter_table('loyalty_otp', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_otp_member', ['member_id', 'created_at'], unique=False)

    op.create_table('staff_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['staff_device.id'], name=op.f('fk_staff_session_device_id_staff_device')),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], name=op.f('fk_staff_session_staff_user_id_staff_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_staff_session_token_hash'))
    )
    with op.batch_alter_table('staff_session', schema=None) as batch_op:
        batch_op.create_index('ix_staff_session_device', ['device_id', 'revoked_at'], unique=False)

    op.create_table('loyalty_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.String(length=400), nullable=False),
    sa.Column('is_alert', sa.Boolean(), nullable=False),
    sa.Column('notified_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('staff_user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_card.id'], name=op.f('fk_loyalty_audit_card_id_loyalty_card')),
    sa.ForeignKeyConstraint(['device_id'], ['staff_device.id'], name=op.f('fk_loyalty_audit_device_id_staff_device')),
    sa.ForeignKeyConstraint(['member_id'], ['loyalty_member.id'], name=op.f('fk_loyalty_audit_member_id_loyalty_member')),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], name=op.f('fk_loyalty_audit_staff_user_id_staff_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_audit'))
    )
    with op.batch_alter_table('loyalty_audit', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_audit_alert', ['is_alert', 'at'], unique=False)
        batch_op.create_index('ix_loyalty_audit_kind', ['kind', 'at'], unique=False)

    op.create_table('loyalty_stamp_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('PURCHASE', 'PAPER_MIGRATION', 'MANUAL_FIX', 'REDEEM', 'REFERRAL', 'UNDO', name='stampreason', native_enum=False), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('staff_user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('undoes_event_id', sa.Integer(), nullable=True),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(reason = 'UNDO') = (undoes_event_id IS NOT NULL)", name=op.f('ck_loyalty_stamp_event_undo_names_target')),
    sa.CheckConstraint('delta <> 0', name=op.f('ck_loyalty_stamp_event_delta_non_zero')),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_card.id'], name=op.f('fk_loyalty_stamp_event_card_id_loyalty_card')),
    sa.ForeignKeyConstraint(['device_id'], ['staff_device.id'], name=op.f('fk_loyalty_stamp_event_device_id_staff_device')),
    sa.ForeignKeyConstraint(['source_event_id'], ['loyalty_stamp_event.id'], name=op.f('fk_loyalty_stamp_event_source_event_id_loyalty_stamp_event')),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], name=op.f('fk_loyalty_stamp_event_staff_user_id_staff_user')),
    sa.ForeignKeyConstraint(['undoes_event_id'], ['loyalty_stamp_event.id'], name=op.f('fk_loyalty_stamp_event_undoes_event_id_loyalty_stamp_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_stamp_event'))
    )
    with op.batch_alter_table('loyalty_stamp_event', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_stamp_event_card', ['card_id', 'created_at'], unique=False)
        batch_op.create_index('ix_loyalty_stamp_event_created', ['created_at'], unique=False)
        batch_op.create_index('ix_loyalty_stamp_event_staff', ['staff_user_id', 'created_at'], unique=False)

    op.create_table('wallet_push_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('done_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=400), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_card.id'], name=op.f('fk_wallet_push_outbox_card_id_loyalty_card')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_push_outbox'))
    )
    with op.batch_alter_table('wallet_push_outbox', schema=None) as batch_op:
        batch_op.create_index('ix_wallet_push_outbox_due', ['done_at', 'next_attempt_at'], unique=False)

    op.create_table('loyalty_reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('STAMP_CARD', 'BIRTHDAY', 'REFERRAL', name='rewardkind', native_enum=False), nullable=False),
    sa.Column('issued_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('redeemed_menu_item_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('staff_user_id', sa.Integer(), nullable=True),
    sa.Column('stamp_event_id', sa.Integer(), nullable=True),
    sa.Column('voided_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('birthday_year', sa.Integer(), nullable=True),
    sa.CheckConstraint("(kind = 'BIRTHDAY') = (birthday_year IS NOT NULL)", name=op.f('ck_loyalty_reward_birthday_year_iff_birthday')),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_card.id'], name=op.f('fk_loyalty_reward_card_id_loyalty_card')),
    sa.ForeignKeyConstraint(['redeemed_menu_item_id'], ['menu_item.id'], name=op.f('fk_loyalty_reward_redeemed_menu_item_id_menu_item')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_loyalty_reward_sale_id_sale')),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_user.id'], name=op.f('fk_loyalty_reward_staff_user_id_staff_user')),
    sa.ForeignKeyConstraint(['stamp_event_id'], ['loyalty_stamp_event.id'], name=op.f('fk_loyalty_reward_stamp_event_id_loyalty_stamp_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_reward')),
    sa.UniqueConstraint('card_id', 'kind', 'birthday_year', name='uq_loyalty_reward_birthday')
    )
    with op.batch_alter_table('loyalty_reward', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_reward_card', ['card_id', 'redeemed_at'], unique=False)
        batch_op.create_index('ix_loyalty_reward_redeemed', ['redeemed_at'], unique=False)

    # ### end Alembic commands ###

    program = sa.table(
        'loyalty_program',
        sa.column('slug', sa.String), sa.column('name', sa.String),
        sa.column('stamps_required', sa.Integer), sa.column('max_stamps_per_scan', sa.Integer),
        sa.column('reward_text', sa.String), sa.column('reward_max_price_pence', sa.Integer),
        sa.column('birthday_reward', sa.Boolean), sa.column('referral_stamps', sa.Integer),
        sa.column('active', sa.Boolean),
        sa.column('created_at', cafeops.db.types.UTCDateTime(timezone=True)),
    )
    op.bulk_insert(program, [{
        'slug': 'stamp', 'name': "Sasha's Corner Rewards", 'stamps_required': 8,
        'max_stamps_per_scan': 3, 'reward_text': 'Any drink, on us',
        'reward_max_price_pence': None, 'birthday_reward': True, 'referral_stamps': 1,
        'active': True, 'created_at': datetime.now(UTC),
    }])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_reward', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_reward_redeemed')
        batch_op.drop_index('ix_loyalty_reward_card')

    op.drop_table('loyalty_reward')
    with op.batch_alter_table('wallet_push_outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_wallet_push_outbox_due')

    op.drop_table('wallet_push_outbox')
    with op.batch_alter_table('loyalty_stamp_event', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_stamp_event_staff')
        batch_op.drop_index('ix_loyalty_stamp_event_created')
        batch_op.drop_index('ix_loyalty_stamp_event_card')

    op.drop_table('loyalty_stamp_event')
    with op.batch_alter_table('loyalty_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_audit_kind')
        batch_op.drop_index('ix_loyalty_audit_alert')

    op.drop_table('loyalty_audit')
    with op.batch_alter_table('staff_session', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_session_device')

    op.drop_table('staff_session')
    with op.batch_alter_table('loyalty_otp', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_otp_member')

    op.drop_table('loyalty_otp')
    with op.batch_alter_table('loyalty_card', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_card_updated')

    op.drop_table('loyalty_card')
    with op.batch_alter_table('loyalty_campaign_delivery', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_delivery_member')

    op.drop_table('loyalty_campaign_delivery')
    op.drop_table('staff_user')
    with op.batch_alter_table('staff_device', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_device_pairing')

    op.drop_table('staff_device')
    op.drop_table('loyalty_program')
    with op.batch_alter_table('loyalty_member', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_member_created')
        batch_op.drop_index('ix_loyalty_member_activity')

    op.drop_table('loyalty_member')
    op.drop_table('loyalty_campaign')
    # ### end Alembic commands ###
