"""loyalty phase 3: points, reward catalogues, several programmes, Lightspeed links

docs/loyalty/CONTRACT.md "Phase 3". New tables: loyalty_reward_option (a programme's
reward catalogue), loyalty_pos_receipt (Lightspeed receipts that named a customer: ids and
keyed hashes, no contacts), loyalty_pos_award (what each receipt earned on each card).
New columns: loyalty_program.kind / points_per_pound / eligibility / description /
reward_ready_label / sort_order, loyalty_member.lightspeed_customer_id (+ when and how it
was linked), loyalty_reward.reward_option_id.

Existing rows: the one programme becomes kind STAMPS with its phase-1 behaviour (NULL
eligibility = drinks, no catalogue = its own reward text). Nothing else is seeded: extra
programmes (a matcha club) exist only through the back office or the dev-only
`cafeops loyalty seed-demo --programmes`.

Autogenerate again proposed re-creating purchase_order's unnamed receipt_asset_id foreign
key; removed, as in b7c1e0a10001 -- this revision touches loyalty tables only.

Revision ID: b7c1e0a10003
Revises: b7c1e0a10002
Create Date: 2026-09-28 14:06:41.646340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cafeops.db.types  # custom column types (Qty, UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = 'b7c1e0a10003'
down_revision: Union[str, Sequence[str], None] = 'b7c1e0a10002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_pos_receipt',
    sa.Column('lightspeed_receipt_id', sa.String(length=80), nullable=False),
    sa.Column('lightspeed_customer_id', sa.String(length=64), nullable=False),
    sa.Column('closed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('customer_label', sa.String(length=60), nullable=True),
    sa.Column('total_pence', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lightspeed_receipt_id', name=op.f('pk_loyalty_pos_receipt'))
    )
    with op.batch_alter_table('loyalty_pos_receipt', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_pos_receipt_closed', ['closed_at'], unique=False)
        batch_op.create_index('ix_loyalty_pos_receipt_customer', ['lightspeed_customer_id', 'closed_at'], unique=False)

    op.create_table('loyalty_reward_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('eligibility', sa.JSON(), nullable=True),
    sa.Column('max_price_pence', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_price_pence IS NULL OR max_price_pence >= 0', name=op.f('ck_loyalty_reward_option_option_cap_non_negative')),
    sa.ForeignKeyConstraint(['program_id'], ['loyalty_program.id'], name=op.f('fk_loyalty_reward_option_program_id_loyalty_program')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_reward_option'))
    )
    with op.batch_alter_table('loyalty_reward_option', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_reward_option_program', ['program_id', 'sort_order'], unique=False)

    op.create_table('loyalty_pos_award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('lightspeed_receipt_id', sa.String(length=80), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AWARDED', 'SKIPPED_STAFF_SCAN', 'NOTHING', 'KEPT', name='posawardstatus', native_enum=False), nullable=False),
    sa.Column('stamp_event_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=400), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('units >= 0', name=op.f('ck_loyalty_pos_award_units_non_negative')),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_card.id'], name=op.f('fk_loyalty_pos_award_card_id_loyalty_card')),
    sa.ForeignKeyConstraint(['stamp_event_id'], ['loyalty_stamp_event.id'], name=op.f('fk_loyalty_pos_award_stamp_event_id_loyalty_stamp_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_pos_award')),
    sa.UniqueConstraint('card_id', 'lightspeed_receipt_id', name='uq_loyalty_pos_award_once')
    )
    with op.batch_alter_table('loyalty_pos_award', schema=None) as batch_op:
        batch_op.create_index('ix_loyalty_pos_award_receipt', ['lightspeed_receipt_id'], unique=False)

    with op.batch_alter_table('loyalty_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lightspeed_customer_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lightspeed_linked_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('lightspeed_link_source', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_loyalty_member_lightspeed_customer_id'), ['lightspeed_customer_id'])

    with op.batch_alter_table('loyalty_program', schema=None) as batch_op:
        # server_default only to fill the existing row; the ORM always writes the value.
        batch_op.add_column(sa.Column('kind', sa.Enum('STAMPS', 'POINTS', name='programkind', native_enum=False), nullable=False, server_default='STAMPS'))
        batch_op.add_column(sa.Column('points_per_pound', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('eligibility', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('reward_ready_label', sa.String(length=60), nullable=False, server_default='Free drink ready'))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_check_constraint(
            op.f('ck_loyalty_program_points_rate_iff_points'),
            "(kind = 'POINTS') = (points_per_pound IS NOT NULL)",
        )

    with op.batch_alter_table('loyalty_reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_option_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_loyalty_reward_reward_option_id_loyalty_reward_option'), 'loyalty_reward_option', ['reward_option_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_reward', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_loyalty_reward_reward_option_id_loyalty_reward_option'), type_='foreignkey')
        batch_op.drop_column('reward_option_id')

    with op.batch_alter_table('loyalty_program', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_loyalty_program_points_rate_iff_points'), type_='check')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('reward_ready_label')
        batch_op.drop_column('description')
        batch_op.drop_column('eligibility')
        batch_op.drop_column('points_per_pound')
        batch_op.drop_column('kind')

    with op.batch_alter_table('loyalty_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_loyalty_member_lightspeed_customer_id'), type_='unique')
        batch_op.drop_column('lightspeed_link_source')
        batch_op.drop_column('lightspeed_linked_at')
        batch_op.drop_column('lightspeed_customer_id')

    with op.batch_alter_table('loyalty_pos_award', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_pos_award_receipt')

    op.drop_table('loyalty_pos_award')
    with op.batch_alter_table('loyalty_reward_option', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_reward_option_program')

    op.drop_table('loyalty_reward_option')
    with op.batch_alter_table('loyalty_pos_receipt', schema=None) as batch_op:
        batch_op.drop_index('ix_loyalty_pos_receipt_customer')
        batch_op.drop_index('ix_loyalty_pos_receipt_closed')

    op.drop_table('loyalty_pos_receipt')
    # ### end Alembic commands ###
