"""initial schema with composition model

Revision ID: b8194b3caaa6
Revises: 
Create Date: 2026-09-19 13:27:39.299174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cafeops.db.types  # custom column types (Qty, UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = 'b8194b3caaa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.Enum('L', 'KG', 'ML', 'G', 'EACH', name='unit', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('tier', sa.Enum('A', 'B', 'C', name='tier', native_enum=False), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('waste_factor', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('current_cost_pence_per_unit', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('current_cost_source', sa.Enum('INVOICE', 'ESTIMATE', 'SUPPLIER_FEED', name='pricesource', native_enum=False), nullable=True),
    sa.Column('source_note', sa.String(length=400), nullable=True),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('delivery_weekdays', sa.JSON(), nullable=False),
    sa.Column('min_order_pence', sa.Integer(), nullable=False),
    sa.Column('order_channel', sa.Enum('EMAIL', 'PORTAL', 'MANUAL', 'BROWSER_AGENT', name='orderchannel', native_enum=False), nullable=False),
    sa.Column('contact', sa.String(length=400), nullable=True),
    sa.Column('order_url', sa.String(length=500), nullable=True),
    sa.Column('agent_instructions', sa.Text(), nullable=True),
    sa.Column('channel_config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('checklist_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OK', 'LOW', name='checkliststatus', native_enum=False), nullable=False),
    sa.Column('responded_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('responded_by', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_response', schema=None) as batch_op:
        batch_op.create_index('ix_checklist_ing_at', ['ingredient_id', 'responded_at'], unique=False)

    op.create_table('ingredient_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('pack_size', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('pack_unit', sa.Enum('L', 'KG', 'ML', 'G', 'EACH', name='unit', native_enum=False), nullable=False),
    sa.Column('pack_cost_pence', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit_pence', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('INVOICE', 'ESTIMATE', 'SUPPLIER_FEED', name='pricesource', native_enum=False), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient_price', schema=None) as batch_op:
        batch_op.create_index('ix_ingredient_price_ing_from', ['ingredient_id', 'effective_from'], unique=False)

    op.create_table('legacy_staged_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_no', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('size_code', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('sell_price_pence', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=160), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('raw_unit', sa.String(length=40), nullable=True),
    sa.Column('role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=True),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('data_quality_flag', sa.String(length=200), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legacy_staged_recipe', schema=None) as batch_op:
        batch_op.create_index('ix_staged_item', ['item_name', 'size_code'], unique=False)
        batch_op.create_index('ix_staged_recipe_no', ['recipe_no'], unique=False)

    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lightspeed_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('size_code', sa.Enum('S', 'M', 'XL', 'ONE', name='sizecode', native_enum=False), nullable=True),
    sa.Column('selected_options', sa.JSON(), nullable=False),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('manual_recipe', sa.Boolean(), nullable=False),
    sa.Column('data_quality_flag', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lightspeed_id'),
    sa.UniqueConstraint('name', 'size_code', name='uq_menu_item_name_size')
    )
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.create_index('ix_menu_item_template', ['template_id', 'size_code'], unique=False)

    op.create_table('modifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('lightspeed_modifier_id', sa.String(length=80), nullable=True),
    sa.Column('action', sa.Enum('SUBSTITUTE', 'ADD', 'SCALE', name='modifieraction', native_enum=False), nullable=False),
    sa.Column('target_role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty_delta', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('qty_multiplier', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lightspeed_modifier_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('par_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('safety_days', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('min_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('max_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('auto_order_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_order_granted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('auto_order_revoked_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('auto_order_reason', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_CONFIRM', 'CONFIRMED', 'SENT', 'RECEIVED', 'CANCELLED', name='postatus', native_enum=False), nullable=False),
    sa.Column('target_delivery_date', sa.Date(), nullable=False),
    sa.Column('created_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=120), nullable=True),
    sa.Column('sent_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('total_pence', sa.Integer(), nullable=False),
    sa.Column('min_order_topped_up', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("(status <> 'SENT') OR (sent_at IS NOT NULL)", name='ck_po_sent_requires_sent_at'),
    sa.CheckConstraint("(status NOT IN ('CONFIRMED', 'SENT', 'RECEIVED')) OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)", name='ck_po_confirmed_requires_human'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index('ix_po_supplier_status', ['supplier_id', 'status'], unique=False)
        batch_op.create_index('ix_po_target_delivery', ['target_delivery_date'], unique=False)

    op.create_table('size_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('S', 'M', 'XL', 'ONE', name='sizecode', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'code', name='uq_size_profile_tpl_code')
    )
    op.create_table('stock_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('counted_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('counted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('counted_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_count', schema=None) as batch_op:
        batch_op.create_index('ix_stock_count_ing_at', ['ingredient_id', 'counted_at'], unique=False)

    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SALE', 'DELIVERY', 'WASTE', 'ADJUSTMENT', 'STAFF', 'COUNT_RESET', name='movementtype', native_enum=False), nullable=False),
    sa.Column('qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('occurred_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movement_ing_at', ['ingredient_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_stock_movement_ref', ['ref_type', 'ref_id'], unique=False)

    op.create_table('supplier_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('pack_size', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('pack_unit', sa.Enum('L', 'KG', 'ML', 'G', 'EACH', name='unit', native_enum=False), nullable=False),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'ingredient_id', 'sku', name='uq_supplier_product_sup_ing_sku')
    )
    op.create_table('template_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty_by_size', sa.JSON(), nullable=False),
    sa.Column('is_substitutable', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['template_component.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_component', schema=None) as batch_op:
        batch_op.create_index('ix_template_component_role', ['template_id', 'role'], unique=False)
        batch_op.create_index('ix_template_component_tpl_from', ['template_id', 'effective_from'], unique=False)

    op.create_table('variant_axis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('COFFEE', 'MILK', 'BASE', 'FLAVOUR', 'TOPPING', 'PACKAGING', 'SUNDRY', name='componentrole', native_enum=False), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['drink_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'name', name='uq_variant_axis_tpl_name')
    )
    op.create_table('drift_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('stock_count_id', sa.Integer(), nullable=False),
    sa.Column('theoretical_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('counted_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('drift_pct', sa.Float(), nullable=False),
    sa.Column('waste_factor_at_count', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('observed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['stock_count_id'], ['stock_count.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_observation', schema=None) as batch_op:
        batch_op.create_index('ix_drift_ing_at', ['ingredient_id', 'observed_at'], unique=False)

    op.create_table('manual_recipe_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_recipe_line', schema=None) as batch_op:
        batch_op.create_index('ix_manual_recipe_item_from', ['menu_item_id', 'effective_from'], unique=False)

    op.create_table('menu_item_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('cost_pence', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('cost_source', sa.Enum('INVOICE', 'ESTIMATE', 'SUPPLIER_FEED', name='pricesource', native_enum=False), nullable=False),
    sa.Column('has_missing_cost', sa.Boolean(), nullable=False),
    sa.Column('ingredient_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id')
    )
    op.create_table('po_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Integer(), nullable=False),
    sa.Column('suggested_packs', sa.Integer(), nullable=False),
    sa.Column('final_packs', sa.Integer(), nullable=False),
    sa.Column('unit_price_pence', sa.Integer(), nullable=False),
    sa.Column('received_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('need_qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=True),
    sa.Column('is_top_up', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('po_line', schema=None) as batch_op:
        batch_op.create_index('ix_po_line_po', ['po_id'], unique=False)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lightspeed_receipt_id', sa.String(length=80), nullable=False),
    sa.Column('lightspeed_line_id', sa.String(length=80), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('qty', cafeops.db.types.Qty(precision=18, scale=6), nullable=False),
    sa.Column('gross_pence', sa.Integer(), nullable=False),
    sa.Column('sold_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.Enum('EPOS', 'DELIVEROO', 'JUST_EAT', 'OTHER', name='salechannel', native_enum=False), nullable=False),
    sa.Column('applied_modifiers', sa.JSON(), nullable=False),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('expanded_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lightspeed_line_id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index('ix_sale_expanded_at', ['expanded_at'], unique=False)
        batch_op.create_index('ix_sale_receipt', ['lightspeed_receipt_id'], unique=False)
        batch_op.create_index('ix_sale_sold_at', ['sold_at'], unique=False)

    op.create_table('variant_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('qty_by_size', sa.JSON(), nullable=True),
    sa.Column('price_delta_pence', sa.Integer(), nullable=False),
    sa.Column('effective_from', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('effective_to', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['axis_id'], ['variant_axis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('axis_id', 'name', 'effective_from', name='uq_variant_option_axis_name')
    )
    with op.batch_alter_table('variant_option', schema=None) as batch_op:
        batch_op.create_index('ix_variant_option_axis_from', ['axis_id', 'effective_from'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant_option', schema=None) as batch_op:
        batch_op.drop_index('ix_variant_option_axis_from')

    op.drop_table('variant_option')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index('ix_sale_sold_at')
        batch_op.drop_index('ix_sale_receipt')
        batch_op.drop_index('ix_sale_expanded_at')

    op.drop_table('sale')
    with op.batch_alter_table('po_line', schema=None) as batch_op:
        batch_op.drop_index('ix_po_line_po')

    op.drop_table('po_line')
    op.drop_table('menu_item_cost')
    with op.batch_alter_table('manual_recipe_line', schema=None) as batch_op:
        batch_op.drop_index('ix_manual_recipe_item_from')

    op.drop_table('manual_recipe_line')
    with op.batch_alter_table('drift_observation', schema=None) as batch_op:
        batch_op.drop_index('ix_drift_ing_at')

    op.drop_table('drift_observation')
    op.drop_table('variant_axis')
    with op.batch_alter_table('template_component', schema=None) as batch_op:
        batch_op.drop_index('ix_template_component_tpl_from')
        batch_op.drop_index('ix_template_component_role')

    op.drop_table('template_component')
    op.drop_table('supplier_product')
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movement_ref')
        batch_op.drop_index('ix_stock_movement_ing_at')

    op.drop_table('stock_movement')
    with op.batch_alter_table('stock_count', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_count_ing_at')

    op.drop_table('stock_count')
    op.drop_table('size_profile')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index('ix_po_target_delivery')
        batch_op.drop_index('ix_po_supplier_status')

    op.drop_table('purchase_order')
    op.drop_table('par_level')
    op.drop_table('modifier')
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_item_template')

    op.drop_table('menu_item')
    with op.batch_alter_table('legacy_staged_recipe', schema=None) as batch_op:
        batch_op.drop_index('ix_staged_recipe_no')
        batch_op.drop_index('ix_staged_item')

    op.drop_table('legacy_staged_recipe')
    with op.batch_alter_table('ingredient_price', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredient_price_ing_from')

    op.drop_table('ingredient_price')
    with op.batch_alter_table('checklist_response', schema=None) as batch_op:
        batch_op.drop_index('ix_checklist_ing_at')

    op.drop_table('checklist_response')
    op.drop_table('supplier')
    op.drop_table('ingredient')
    op.drop_table('drink_template')
    # ### end Alembic commands ###
