"""payment_day: daily takings from a payment report

Revision ID: dff1f404b11c
Revises: 3c41d7a9e2b0
Create Date: 2026-09-24 20:21:34.059450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cafeops.db.types  # custom column types (Qty, UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = 'dff1f404b11c'
down_revision: Union[str, Sequence[str], None] = '3c41d7a9e2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'VOUCHER', 'ACCOUNT', 'OTHER', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('gross_pence', sa.Integer(), nullable=False),
    sa.Column('refunds_pence', sa.Integer(), nullable=True),
    sa.Column('fees_pence', sa.Integer(), nullable=True),
    sa.Column('discounts_pence', sa.Integer(), nullable=True),
    sa.Column('transactions', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('CSV_UPLOAD', 'POS_API', 'MANUAL', name='paymentsourcekind', native_enum=False), nullable=False),
    sa.Column('source_ref', sa.String(length=400), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('imported_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_day')),
    sa.UniqueConstraint('business_date', 'method', 'source', name='uq_payment_day_date_method_source')
    )
    with op.batch_alter_table('payment_day', schema=None) as batch_op:
        batch_op.create_index('ix_payment_day_date', ['business_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_day', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_day_date')

    op.drop_table('payment_day')
    # ### end Alembic commands ###
