"""online ordering: click & collect (docs/shop/CONTRACT.md §2)

Eleven new `shop_*` tables: the one-row settings, the catalogue overlay (banners,
categories keyed to `menu_category.name`, products keyed to `menu_item.name`, option
groups + options + attachments, upsells) and orders (order, line, event).

Data step, plain SQL through `op.get_bind()` so it also runs on an empty database:

1. the settings row (`id = 1`, shop OFF, Mon-Sat 09:00-19:00, Sun 09:00-17:00);
2. `shop_category` / `shop_product` synced from the live menu (same rule as
   `services/shop/catalog`: insert what is missing, never delete);
3. the three option groups the shop needs on day one -- Milk (SINGLE, required, every
   DRINKS category; options linked to the ops `modifier` by case-insensitive name),
   Extras (MULTI, collapsed), Customise (MULTI);
4. one BASKET upsell, "Fancy a cake?", with the first four visible products in
   Cakes & bakes (empty list when that category has none).

The enum additions `SaleChannel.WEB` / `SaleSource.ONLINE` need nothing here: enums
are VARCHAR without CHECK and the names fit the column width.

Autogenerate also proposed re-creating purchase_order's unnamed receipt_asset_id
foreign key; that is unrelated drift and was removed, as in every revision since.

Revision ID: f2a3b4c5d6e7
Revises: e6f2b1c40a53
Create Date: 2026-09-28 23:52:03.586323

"""
import re
from collections.abc import Sequence
from datetime import UTC, datetime

import cafeops.db.types  # custom column types (Qty, UTCDateTime)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine import Connection

# revision identifiers, used by Alembic.
revision: str = 'f2a3b4c5d6e7'
down_revision: str | Sequence[str] | None = 'e6f2b1c40a53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_option_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('prompt', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.Enum('SINGLE', 'MULTI', name='optionkind', native_enum=False), nullable=False),
    sa.Column('layout', sa.Enum('TILES', 'PHOTO_TILES', 'CHECKLIST', name='optionlayout', native_enum=False), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('min_select', sa.Integer(), nullable=False),
    sa.Column('max_select', sa.Integer(), nullable=True),
    sa.Column('collapsed', sa.Boolean(), nullable=False),
    sa.Column('applies_to_categories', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_select IS NULL OR max_select >= 1', name=op.f('ck_shop_option_group_shop_option_group_max_positive')),
    sa.CheckConstraint('min_select >= 0', name=op.f('ck_shop_option_group_shop_option_group_min_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_option_group'))
    )
    op.create_table('shop_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('closed_message', sa.String(length=300), nullable=False),
    sa.Column('hero_title', sa.String(length=120), nullable=False),
    sa.Column('hero_subtitle', sa.String(length=300), nullable=False),
    sa.Column('takeaway_enabled', sa.Boolean(), nullable=False),
    sa.Column('eat_in_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_dining', sa.Enum('TAKEAWAY', 'EAT_IN', name='diningoption', native_enum=False), nullable=False),
    sa.Column('lead_minutes', sa.Integer(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('max_orders_per_slot', sa.Integer(), nullable=False),
    sa.Column('days_ahead', sa.Integer(), nullable=False),
    sa.Column('hours', sa.JSON(), nullable=False),
    sa.Column('last_order_minutes_before_close', sa.Integer(), nullable=False),
    sa.Column('closures', sa.JSON(), nullable=False),
    sa.Column('pay_at_counter', sa.Boolean(), nullable=False),
    sa.Column('pay_online', sa.Boolean(), nullable=False),
    sa.Column('kcal_notice', sa.String(length=200), nullable=False),
    sa.Column('allergen_notice', sa.Text(), nullable=False),
    sa.Column('collection_note', sa.String(length=300), nullable=False),
    sa.Column('terms_url', sa.String(length=300), nullable=False),
    sa.Column('loyalty_stamps_online', sa.Boolean(), nullable=False),
    sa.Column('notify_telegram', sa.Boolean(), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('days_ahead >= 0', name=op.f('ck_shop_settings_shop_days_ahead_non_negative')),
    sa.CheckConstraint('lead_minutes >= 0', name=op.f('ck_shop_settings_shop_lead_non_negative')),
    sa.CheckConstraint('max_orders_per_slot >= 0', name=op.f('ck_shop_settings_shop_capacity_non_negative')),
    sa.CheckConstraint('slot_minutes >= 1', name=op.f('ck_shop_settings_shop_slot_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_settings'))
    )
    op.create_table('shop_upsell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Enum('ITEM_PAGE', 'BASKET', name='upsellplacement', native_enum=False), nullable=False),
    sa.Column('heading', sa.String(length=80), nullable=False),
    sa.Column('product_ids', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_upsell'))
    )
    op.create_table('shop_banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('photo_asset_id', sa.Integer(), nullable=True),
    sa.Column('link_href', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['photo_asset_id'], ['media_asset.id'], name=op.f('fk_shop_banner_photo_asset_id_media_asset'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_banner'))
    )
    op.create_table('shop_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ops_name', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('blurb', sa.String(length=300), nullable=True),
    sa.Column('photo_asset_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_asset_id'], ['media_asset.id'], name=op.f('fk_shop_category_photo_asset_id_media_asset'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_category')),
    sa.UniqueConstraint('ops_name', name=op.f('uq_shop_category_ops_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_shop_category_slug'))
    )
    op.create_table('shop_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category_ops_name', sa.String(length=80), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=False),
    sa.Column('dietary', sa.JSON(), nullable=False),
    sa.Column('default_size', sa.String(length=4), nullable=True),
    sa.Column('ingredients_text', sa.String(length=600), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('kcal_by_size', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('nutrition', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('photo_asset_id', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=30), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_asset_id'], ['media_asset.id'], name=op.f('fk_shop_product_photo_asset_id_media_asset'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_product')),
    sa.UniqueConstraint('item_name', name=op.f('uq_shop_product_item_name'))
    )
    with op.batch_alter_table('shop_product', schema=None) as batch_op:
        batch_op.create_index('ix_shop_product_category', ['category_ops_name', 'sort_order'], unique=False)

    op.create_table('shop_product_option_group',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['shop_option_group.id'], name=op.f('fk_shop_product_option_group_group_id_shop_option_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], name=op.f('fk_shop_product_option_group_product_id_shop_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'group_id', name=op.f('pk_shop_product_option_group'))
    )
    op.create_table('shop_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('price_delta_pence', sa.Integer(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('modifier_id', sa.Integer(), nullable=True),
    sa.Column('photo_asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['shop_option_group.id'], name=op.f('fk_shop_option_group_id_shop_option_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifier.id'], name=op.f('fk_shop_option_modifier_id_modifier'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_asset_id'], ['media_asset.id'], name=op.f('fk_shop_option_photo_asset_id_media_asset'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_option'))
    )
    with op.batch_alter_table('shop_option', schema=None) as batch_op:
        batch_op.create_index('ix_shop_option_group', ['group_id', 'sort_order'], unique=False)

    op.create_table('shop_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'NEW', 'ACCEPTED', 'PREPARING', 'READY', 'COLLECTED', 'CANCELLED', 'REJECTED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('dining', sa.Enum('TAKEAWAY', 'EAT_IN', name='diningoption', native_enum=False), nullable=False),
    sa.Column('asap', sa.Boolean(), nullable=False),
    sa.Column('requested_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('placed_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ready_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('collected_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('cancelled_by', sa.String(length=40), nullable=True),
    sa.Column('customer_name', sa.String(length=80), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=254), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('allergy_ack', sa.Boolean(), nullable=False),
    sa.Column('subtotal_pence', sa.Integer(), nullable=False),
    sa.Column('discount_pence', sa.Integer(), nullable=False),
    sa.Column('total_pence', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('COUNTER', 'ONLINE', name='shoppaymentmethod', native_enum=False), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'REFUNDED', 'FAILED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('payment_ref', sa.String(length=120), nullable=True),
    sa.Column('paid_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sale_receipt_id', sa.String(length=80), nullable=True),
    sa.Column('stamp_event_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('staff_note', sa.String(length=300), nullable=True),
    sa.Column('updated_at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('customer_phone IS NOT NULL OR customer_email IS NOT NULL', name=op.f('ck_shop_order_shop_order_has_contact')),
    sa.CheckConstraint('discount_pence >= 0', name=op.f('ck_shop_order_shop_order_discount_non_negative')),
    sa.CheckConstraint('subtotal_pence >= 0', name=op.f('ck_shop_order_shop_order_subtotal_non_negative')),
    sa.CheckConstraint('total_pence >= 0', name=op.f('ck_shop_order_shop_order_total_non_negative')),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_card.id'], name=op.f('fk_shop_order_card_id_loyalty_card')),
    sa.ForeignKeyConstraint(['member_id'], ['loyalty_member.id'], name=op.f('fk_shop_order_member_id_loyalty_member')),
    sa.ForeignKeyConstraint(['reward_id'], ['loyalty_reward.id'], name=op.f('fk_shop_order_reward_id_loyalty_reward')),
    sa.ForeignKeyConstraint(['stamp_event_id'], ['loyalty_stamp_event.id'], name=op.f('fk_shop_order_stamp_event_id_loyalty_stamp_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_order')),
    sa.UniqueConstraint('access_token', name=op.f('uq_shop_order_access_token')),
    sa.UniqueConstraint('code', name=op.f('uq_shop_order_code'))
    )
    with op.batch_alter_table('shop_order', schema=None) as batch_op:
        batch_op.create_index('ix_shop_order_member', ['member_id'], unique=False)
        batch_op.create_index('ix_shop_order_placed_at', ['placed_at'], unique=False)
        batch_op.create_index('ix_shop_order_requested_at', ['requested_at'], unique=False)
        batch_op.create_index('ix_shop_order_status', ['status'], unique=False)

    op.create_table('shop_order_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('at', cafeops.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.String(length=400), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_order.id'], name=op.f('fk_shop_order_event_order_id_shop_order'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_order_event'))
    )
    with op.batch_alter_table('shop_order_event', schema=None) as batch_op:
        batch_op.create_index('ix_shop_order_event_order', ['order_id', 'at'], unique=False)

    op.create_table('shop_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('size_label', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_pence', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('line_total_pence', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty >= 1', name=op.f('ck_shop_order_line_shop_order_line_qty_positive')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_shop_order_line_menu_item_id_menu_item')),
    sa.ForeignKeyConstraint(['order_id'], ['shop_order.id'], name=op.f('fk_shop_order_line_order_id_shop_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], name=op.f('fk_shop_order_line_product_id_shop_product'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_order_line'))
    )
    with op.batch_alter_table('shop_order_line', schema=None) as batch_op:
        batch_op.create_index('ix_shop_order_line_order', ['order_id'], unique=False)

    # ### end Alembic commands ###

    _seed(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_order_line', schema=None) as batch_op:
        batch_op.drop_index('ix_shop_order_line_order')

    op.drop_table('shop_order_line')
    with op.batch_alter_table('shop_order_event', schema=None) as batch_op:
        batch_op.drop_index('ix_shop_order_event_order')

    op.drop_table('shop_order_event')
    with op.batch_alter_table('shop_order', schema=None) as batch_op:
        batch_op.drop_index('ix_shop_order_status')
        batch_op.drop_index('ix_shop_order_requested_at')
        batch_op.drop_index('ix_shop_order_placed_at')
        batch_op.drop_index('ix_shop_order_member')

    op.drop_table('shop_order')
    with op.batch_alter_table('shop_option', schema=None) as batch_op:
        batch_op.drop_index('ix_shop_option_group')

    op.drop_table('shop_option')
    op.drop_table('shop_product_option_group')
    with op.batch_alter_table('shop_product', schema=None) as batch_op:
        batch_op.drop_index('ix_shop_product_category')

    op.drop_table('shop_product')
    op.drop_table('shop_category')
    op.drop_table('shop_banner')
    op.drop_table('shop_upsell')
    op.drop_table('shop_settings')
    op.drop_table('shop_option_group')
    # ### end Alembic commands ###


# --------------------------------------------------------------------------
# data step
# --------------------------------------------------------------------------

_ALLERGEN_NOTICE = (
    "Our drinks and food are prepared in a small kitchen where milk, gluten, nuts, "
    "soya, egg, sesame and sulphites are all handled, so we cannot guarantee any item "
    "is free from them. If you have an allergy or intolerance, tell us at the counter "
    "before we make your order and we will do our best to help."
)

_HOURS = [
    {"weekday": 0, "open": "09:00", "close": "19:00"},
    {"weekday": 1, "open": "09:00", "close": "19:00"},
    {"weekday": 2, "open": "09:00", "close": "19:00"},
    {"weekday": 3, "open": "09:00", "close": "19:00"},
    {"weekday": 4, "open": "09:00", "close": "19:00"},
    {"weekday": 5, "open": "09:00", "close": "19:00"},
    {"weekday": 6, "open": "09:00", "close": "17:00"},
]

#: (name, prompt, kind, layout, required, min, max, collapsed, applies_to_drinks, options)
#: option = (name, description, price_delta_pence, is_default)
_GROUPS: list[tuple[str, str, str, str, bool, int, int | None, bool, bool, list[tuple[str, str | None, int, bool]]]] = [
    (
        "Milk", "Choose your milk", "SINGLE", "TILES", True, 1, 1, False, True,
        [
            ("Whole milk", None, 0, True),
            ("Skimmed milk", None, 0, False),
            ("Oat milk", None, 50, False),
            ("Almond milk", None, 50, False),
            ("Coconut milk", None, 50, False),
            ("Soya milk", None, 50, False),
        ],
    ),
    (
        "Extras", "Add extras and syrups", "MULTI", "TILES", False, 0, None, True, True,
        [
            ("Extra shot", "Double the caffeine", 60, False),
            ("Extra syrup pump", None, 50, False),
            ("Whipped cream", None, 50, False),
            ("Decaf", None, 0, False),
        ],
    ),
    (
        "Customise", None, "MULTI", "CHECKLIST", False, 0, None, False, True,
        [
            ("Extra hot", None, 0, False),
            ("No lid", None, 0, False),
            ("Cinnamon dusting", None, 0, False),
            ("Chocolate dusting", None, 0, False),
        ],
    ),
]

#: Ops modifier names that mean the same as a shop option name (case-insensitive).
_MODIFIER_ALIASES = {"soya milk": ("soy milk", "soya milk"), "oat milk": ("oat milk",), "almond milk": ("almond milk",)}


def _slugify(name: str) -> str:
    s = name.casefold().replace("&", " and ")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-") or "category"


def _tables() -> dict[str, sa.Table]:
    """Lightweight table objects so JSON and UTCDateTime values bind through their types."""
    meta = sa.MetaData()
    dt = cafeops.db.types.UTCDateTime
    return {
        "settings": sa.Table(
            "shop_settings", meta,
            sa.Column("id", sa.Integer), sa.Column("enabled", sa.Boolean),
            sa.Column("closed_message", sa.String), sa.Column("hero_title", sa.String),
            sa.Column("hero_subtitle", sa.String), sa.Column("takeaway_enabled", sa.Boolean),
            sa.Column("eat_in_enabled", sa.Boolean), sa.Column("default_dining", sa.String),
            sa.Column("lead_minutes", sa.Integer), sa.Column("slot_minutes", sa.Integer),
            sa.Column("max_orders_per_slot", sa.Integer), sa.Column("days_ahead", sa.Integer),
            sa.Column("hours", sa.JSON), sa.Column("last_order_minutes_before_close", sa.Integer),
            sa.Column("closures", sa.JSON), sa.Column("pay_at_counter", sa.Boolean),
            sa.Column("pay_online", sa.Boolean), sa.Column("kcal_notice", sa.String),
            sa.Column("allergen_notice", sa.Text), sa.Column("collection_note", sa.String),
            sa.Column("terms_url", sa.String), sa.Column("loyalty_stamps_online", sa.Boolean),
            sa.Column("notify_telegram", sa.Boolean), sa.Column("updated_at", dt),
        ),
        "category": sa.Table(
            "shop_category", meta,
            sa.Column("id", sa.Integer), sa.Column("ops_name", sa.String), sa.Column("name", sa.String),
            sa.Column("slug", sa.String), sa.Column("sort_order", sa.Integer),
            sa.Column("visible", sa.Boolean), sa.Column("updated_at", dt),
        ),
        "product": sa.Table(
            "shop_product", meta,
            sa.Column("id", sa.Integer), sa.Column("item_name", sa.String),
            sa.Column("category_ops_name", sa.String), sa.Column("allergens", sa.JSON),
            sa.Column("dietary", sa.JSON), sa.Column("sort_order", sa.Integer),
            sa.Column("visible", sa.Boolean), sa.Column("available", sa.Boolean),
            sa.Column("featured", sa.Boolean), sa.Column("updated_at", dt),
        ),
        "group": sa.Table(
            "shop_option_group", meta,
            sa.Column("id", sa.Integer), sa.Column("name", sa.String), sa.Column("prompt", sa.String),
            sa.Column("kind", sa.String), sa.Column("layout", sa.String),
            sa.Column("required", sa.Boolean), sa.Column("min_select", sa.Integer),
            sa.Column("max_select", sa.Integer), sa.Column("collapsed", sa.Boolean),
            sa.Column("applies_to_categories", sa.JSON), sa.Column("sort_order", sa.Integer),
            sa.Column("active", sa.Boolean), sa.Column("updated_at", dt),
        ),
        "option": sa.Table(
            "shop_option", meta,
            sa.Column("id", sa.Integer), sa.Column("group_id", sa.Integer), sa.Column("name", sa.String),
            sa.Column("description", sa.String), sa.Column("price_delta_pence", sa.Integer),
            sa.Column("kcal", sa.Integer), sa.Column("is_default", sa.Boolean),
            sa.Column("available", sa.Boolean), sa.Column("sort_order", sa.Integer),
            sa.Column("modifier_id", sa.Integer),
        ),
        "upsell": sa.Table(
            "shop_upsell", meta,
            sa.Column("id", sa.Integer), sa.Column("placement", sa.String),
            sa.Column("heading", sa.String), sa.Column("product_ids", sa.JSON),
            sa.Column("sort_order", sa.Integer), sa.Column("active", sa.Boolean),
        ),
    }


def _seed(bind: Connection) -> None:
    now = datetime.now(UTC)
    t = _tables()

    # 1. settings
    bind.execute(
        t["settings"].insert().values(
            id=1,
            enabled=False,
            closed_message="Online ordering is taking a short break. Order at the counter.",
            hero_title="Order ahead. Collect from Commercial Street.",
            hero_subtitle=(
                "Takeaway made to order. Skip the queue: pay here or at the counter, "
                "we'll have it ready."
            ),
            takeaway_enabled=True,
            eat_in_enabled=True,
            default_dining="TAKEAWAY",
            lead_minutes=10,
            slot_minutes=10,
            max_orders_per_slot=6,
            days_ahead=0,
            hours=_HOURS,
            last_order_minutes_before_close=20,
            closures=[],
            pay_at_counter=True,
            pay_online=False,
            kcal_notice="Adults need around 2000 kcal a day.",
            allergen_notice=_ALLERGEN_NOTICE,
            collection_note=(
                "Collect from the counter at 23 Commercial Street. Say your name or show "
                "the order code."
            ),
            terms_url="/privacy",
            loyalty_stamps_online=True,
            notify_telegram=True,
            updated_at=now,
        )
    )

    # 2. categories from menu_category; products from active menu_item names
    categories = bind.execute(
        sa.text("SELECT name, kind, sort_order FROM menu_category ORDER BY sort_order, id")
    ).fetchall()
    drink_slugs: list[str] = []
    seen_slugs: set[str] = set()
    for name, kind, sort_order in categories:
        slug = _slugify(name)
        base, n = slug, 2
        while slug in seen_slugs:
            slug, n = f"{base}-{n}", n + 1
        seen_slugs.add(slug)
        bind.execute(
            t["category"].insert().values(
                ops_name=name, name=name, slug=slug, sort_order=int(sort_order or 0),
                visible=True, updated_at=now,
            )
        )
        if kind == "DRINKS":
            drink_slugs.append(slug)

    items = bind.execute(
        sa.text(
            "SELECT name, category FROM menu_item WHERE active = 1 ORDER BY id"
        )
    ).fetchall()
    seen_names: set[str] = set()
    sort = 0
    for name, category in items:
        if name in seen_names:
            continue
        seen_names.add(name)
        sort += 10
        bind.execute(
            t["product"].insert().values(
                item_name=name,
                category_ops_name=(category or "").strip() or None,
                allergens=[], dietary=[], sort_order=sort,
                visible=True, available=True, featured=False,
                updated_at=now,
            )
        )

    # 3. option groups, options linked to ops modifiers by name
    modifiers = {
        str(name).strip().casefold(): int(mid)
        for mid, name in bind.execute(
            sa.text("SELECT id, name FROM modifier WHERE is_active = 1")
        ).fetchall()
    }
    for gi, (gname, prompt, kind, layout, required, mn, mx, collapsed, drinks, options) in enumerate(_GROUPS):
        result = bind.execute(
            t["group"].insert().values(
                name=gname, prompt=prompt, kind=kind, layout=layout, required=required,
                min_select=mn, max_select=mx, collapsed=collapsed,
                applies_to_categories=list(drink_slugs) if drinks else [],
                sort_order=(gi + 1) * 10, active=True, updated_at=now,
            )
        )
        group_id = result.inserted_primary_key[0] if result.inserted_primary_key else None
        if group_id is None:
            group_id = bind.execute(
                sa.text("SELECT id FROM shop_option_group WHERE name = :n"), {"n": gname}
            ).scalar_one()
        for oi, (oname, desc, delta, default) in enumerate(options):
            key = oname.casefold()
            modifier_id: int | None = None
            for alias in _MODIFIER_ALIASES.get(key, (key,)):
                if alias in modifiers:
                    modifier_id = modifiers[alias]
                    break
            bind.execute(
                t["option"].insert().values(
                    group_id=group_id, name=oname, description=desc,
                    price_delta_pence=delta, kcal=None, is_default=default, available=True,
                    sort_order=(oi + 1) * 10, modifier_id=modifier_id,
                )
            )

    # 4. one basket upsell with the first four visible Cakes & bakes products
    cake_ids = [
        int(pid)
        for (pid,) in bind.execute(
            sa.text(
                "SELECT id FROM shop_product WHERE category_ops_name = :c AND visible = 1 "
                "ORDER BY sort_order, id LIMIT 4"
            ),
            {"c": "Cakes & bakes"},
        ).fetchall()
    ]
    bind.execute(
        t["upsell"].insert().values(
            placement="BASKET", heading="Fancy a cake?", product_ids=cake_ids,
            sort_order=10, active=True,
        )
    )
