"""serve / api-fixtures / doctor / scheduler-run -- the processes and the health check
(spec 10)."""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Annotated

import typer
from rich.table import Table

from cafeops.cli._common import console
from cafeops.config import settings
from cafeops.db.base import session_scope


def serve(
    host: Annotated[str, typer.Option("--host", help="Bind address.")] = "127.0.0.1",
    port: Annotated[int, typer.Option("--port", help="Bind port.")] = 8000,
    reload: Annotated[
        bool, typer.Option("--reload/--no-reload", help="Auto-reload on code change.")
    ] = False,
) -> None:
    """Run the read-only back-office API under uvicorn. ONE worker, deliberately.

    Spec 3: one box, one SQLite file, one writer. A second worker would contend on the
    same file and make things worse, so there is no `--workers` flag to reach for
    (ARCHITECTURE.md 8F.8). TLS belongs to Caddy in front, not here.

    Binds to loopback by default. The app is behind a reverse proxy in the real
    deployment, and a back office listening on 0.0.0.0 by default is one firewall rule
    away from being the whole business on the open internet.
    """
    import uvicorn

    from cafeops.api.security import api_password

    if api_password() is None:
        console.print(
            "[yellow]CAFEOPS_API_PASSWORD is not set.[/yellow] The server will start, but "
            "every endpoint except /api/health will answer 503 rather than serve the "
            "business unauthenticated. Set it in .env and restart.\n"
            "[dim]Spec 1: a single shared password, no user management.[/dim]"
        )
    console.print(
        f"[bold]cafeops api[/bold] on http://{host}:{port}  "
        f"docs http://{host}:{port}/api/docs  db {settings.database_url}"
    )
    uvicorn.run(
        "cafeops.api.app:app",
        host=host,
        port=port,
        reload=reload,
        workers=1,
        log_level="info",
    )


def api_fixtures(
    out: Annotated[
        Path, typer.Option("--out", help="Directory to write the JSON fixtures into.")
    ] = Path("web/fixtures"),
    password: Annotated[
        str | None,
        typer.Option(
            "--password",
            help="Shared password to present. Defaults to CAFEOPS_API_PASSWORD.",
        ),
    ] = None,
    allow_errors: Annotated[
        bool,
        typer.Option(
            "--allow-errors",
            help="Publish even if an endpoint did not return 200. Only useful when the "
            "error response IS the fixture you want.",
        ),
    ] = False,
) -> None:
    """Dump one REAL JSON response per endpoint, so the frontend can build against fixtures.

    Not hand-written samples: the app is driven in-process over ASGI and each file is
    what the endpoint actually returned. A fixture that is generated by running the code
    cannot drift from it silently, which a checked-in sample always eventually does.

    Auth is exercised rather than bypassed -- the dump presents the password as a client
    would, so a 401 in `index.json` means the frontend would get one too.
    """
    from cafeops.api.examples import dump_examples
    from cafeops.api.security import api_password

    secret = password or api_password()
    if secret is None:
        console.print(
            "[red]No password, so every protected endpoint would answer 503.[/red] "
            "Pass --password or set CAFEOPS_API_PASSWORD.\n"
            "[dim]Refusing rather than writing error bodies: these files are what the "
            "frontend builds against, and a directory of 503s looks exactly like a "
            "directory of fixtures until a screen renders blank.[/dim]"
        )
        raise typer.Exit(2)

    # Build into a scratch directory and publish only once every endpoint answered 200.
    # Writing in place meant a failed dump replaced good fixtures with error bodies --
    # which happened, and cost somebody a restore from backup. The artefact is either
    # complete or the old one is still there.
    staging = out.parent / f".{out.name}.staging"
    if staging.exists():
        shutil.rmtree(staging)
    written = dump_examples(staging, password=secret)
    bad_now = [name for name, status, _ in written if status != 200]
    if bad_now and not allow_errors:
        console.print(
            f"[red]{len(bad_now)} endpoint(s) did not return 200: "
            f"{', '.join(bad_now)}[/red]\n"
            f"[dim]Nothing was published; {out} is untouched. The staged attempt is in "
            f"{staging} if you want to look at it. Pass --allow-errors to publish "
            "anyway, which is only useful when the error IS the fixture.[/dim]"
        )
        raise typer.Exit(1)

    # Merge rather than replace: index.json may hold entries this command does not
    # generate (recorded by hand for a screen whose endpoint had no example yet), and a
    # wholesale replace deleted them. See `publish_examples`.
    from cafeops.api.examples import publish_examples

    kept = publish_examples(staging, out)
    shutil.rmtree(staging)
    table = Table(title=f"{len(written)} fixture(s) -> {out}", title_style="bold")
    table.add_column("Endpoint", no_wrap=True)
    table.add_column("Status", justify="right")
    table.add_column("Bytes", justify="right")
    for name, status, size in written:
        style = "green" if status == 200 else "red"
        table.add_row(name, f"[{style}]{status}[/{style}]", f"{size:,}")
    console.print(table)
    bad = [name for name, status, _ in written if status != 200]
    if bad:
        console.print(f"[red]{len(bad)} endpoint(s) did not return 200: {', '.join(bad)}[/red]")
    if kept:
        console.print(
            f"[dim]Kept {len(kept)} existing entr{'y' if len(kept) == 1 else 'ies'} this "
            f"command does not generate: {', '.join(kept)}[/dim]"
        )
    console.print("[dim]index.json lists every file with the query behind it.[/dim]")


def doctor(
    verbose: Annotated[
        bool, typer.Option("--verbose", help="Show the checks that passed as well.")
    ] = False,
) -> None:
    """Is this install operable? Run this first when something looks wrong.

    Exits non-zero only on FAIL, so it is safe from cron. A WARN means a number is
    resting on a guess worth replacing; it does not mean the system is broken.
    """
    from cafeops.services.doctor import Severity, run_doctor

    with session_scope() as session:
        report = run_doctor(session)

    style = {
        Severity.FAIL: "bold red",
        Severity.WARN: "yellow",
        Severity.INFO: "dim",
        Severity.OK: "green",
    }
    shown = [c for c in report.checks if verbose or c.severity is not Severity.OK]
    table = Table(title="cafeops doctor", title_style="bold", show_lines=False)
    table.add_column("", justify="center", no_wrap=True)
    table.add_column("Check", no_wrap=True)
    table.add_column("Detail")
    for check in shown:
        table.add_row(
            f"[{style[check.severity]}]{check.severity.value}[/]",
            check.name,
            check.detail + (f"\n[cyan]-> {check.fix}[/cyan]" if check.fix else ""),
        )
    if shown:
        console.print(table)

    passed = sum(1 for c in report.checks if c.severity is Severity.OK)
    if report.is_operable:
        console.print(
            f"[green]Operable.[/green] {passed} check(s) passed, "
            f"{len(report.warnings)} warning(s)."
            + ("" if verbose else "  [dim]--verbose shows what passed.[/dim]")
        )
    else:
        console.print(
            f"[bold red]NOT operable.[/bold red] {len(report.failures)} failure(s) — "
            "the system is producing wrong numbers or will not run. Fix those first."
        )
    raise typer.Exit(report.exit_code())


def scheduler_run() -> None:
    """Run the APScheduler process in the foreground. This is a long-running unit.

    Exists so the scheduler starts the same way every other process does --
    `cafeops serve`, `cafeops bot-run`, `cafeops scheduler-run` -- rather than through
    `python -c "from cafeops.jobs.scheduler import main; main()"`. A deployment that has
    to reach past the CLI into a module path is one rename away from a service that
    silently fails to start, and the scheduler failing silently means no sync, no
    expansion, no expiry sweep and no draft orders, with nothing on screen to say so.

    Use `cafeops jobs` to see what is scheduled and why, without starting anything.
    """
    from cafeops.jobs.scheduler import main as scheduler_main

    console.print(
        "[bold]Starting the scheduler.[/bold] Ctrl-C to stop. "
        "Run [cyan]cafeops jobs[/cyan] to see the schedule without starting it."
    )
    scheduler_main()


def register(app: typer.Typer) -> None:
    app.command()(serve)
    app.command(name="api-fixtures")(api_fixtures)
    app.command()(doctor)
    app.command(name="scheduler-run")(scheduler_run)
